        CPU     8086
        ORG     0h
InterruptVectorTable:
        ; Internal x86 Interrupts:
        dd      0 ; Reserved (Div err)  ; Int 00h
        dd      0 ; Reserved (Step)     ; Int 01h
        dd      0 ; Reserved (NMI)      ; Int 02h
        dd      0 ; Reserved (Break)    ; Int 03h
        dd      0 ; Reserved (Overflow) ; Int 04h
        dd      0                       ; Int 05h
        dd      0                       ; Int 06h
        dd      0                       ; Int 07h
        ; Hardware Interrupts:
        dd      reset ; Reset               ; Int 08h (IRQ 0)
        dd      tick ; Tick                ; Int 09h (IRQ 1)
        dd      keyboard ; Keyboard            ; Int 0Ah (IRQ 2)
        dd      0 ; Simptris Game Over  ; Int 0Bh (IRQ 3)
        dd      0 ; Simptris New Piece  ; Int 0Ch (IRQ 4)
        dd      0 ; Simptris Received   ; Int 0Dh (IRQ 5)
        dd      0 ; Simptris Touchdown  ; Int 0Eh (IRQ 6)
        dd      0 ; Simptris Clear      ; Int 0Fh (IRQ 7)
        ; Software Interrupts:
        dd      0 ; Reserved (PC BIOS)  ; Int 10h
        dd      0                       ; Int 11h
        dd      0                       ; Int 12h
        dd      0                       ; Int 13h
        dd      0                       ; Int 14h
        dd      0                       ; Int 15h
        dd      0                       ; Int 16h
        dd      0                       ; Int 17h
        dd      0                       ; Int 18h
        dd      0                       ; Int 19h
        dd      0                       ; Int 1Ah
        dd      0                       ; Int 1Bh
        dd      0                       ; Int 1Ch
        dd      0                       ; Int 1Dh
        dd      0                       ; Int 1Eh
        dd      0                       ; Int 1Fh
        dd      0                       ; Int 20h
        dd      0 ; Reserved (DOS)      ; Int 21h
        dd      0 ; Simptris Services   ; Int 22h
        dd      0                       ; Int 23h
        dd      0                       ; Int 24h
        dd      0                       ; Int 25h
        dd      0                       ; Int 26h
        dd      0                       ; Int 27h
        dd      0                       ; Int 28h
        dd      0                       ; Int 29h
        dd      0                       ; Int 2Ah
        dd      0                       ; Int 2Bh
        dd      0                       ; Int 2Ch
        dd      0                       ; Int 2Dh
        dd      0                       ; Int 2Eh
        dd      0                       ; Int 2Fh
KeyBuffer:                              ; Address 0xC0
        dw      0
NewPieceType:                           ; Address 0xC2
        dw      0
NewPieceID:                             ; Address 0xC4
        dw      0
NewPieceOrientation:                    ; Address 0xC6
        dw      0
NewPieceColumn:                         ; Address 0xC8
        dw      0
TouchdownID:                            ; Address 0xCA
	dw	0
ScreenBitMap0:                          ; Address 0xCC
        dw      0
ScreenBitMap1:
        dw      0
ScreenBitMap2:
        dw      0
ScreenBitMap3:
        dw      0
ScreenBitMap4:
        dw      0
ScreenBitMap5:
        dw      0
TIMES   100h-($-$$) db  0               ; Fill up to (but not including) address 100h with 0
	jmp	main
; This file contains support routines for 32-bit on the 8086.
; It is intended for use code generated by the C86 compiler.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SR_asldiv:			; l1 /= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_ldiv
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmod:			; l1 %= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmod
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmul:			; l1 *= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmul
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshl:			; l1 <<= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshl
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshr:			; l1 >>= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshr
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


SR_asuldiv:			; u1 /= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_uldiv
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asilmod:			; u1 %= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ilmod
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulmul:			; u1 *= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulmul
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshl:			; u1 << u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshl
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshr:			; u1 >> u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshr
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


; Main 32-bit routines begin here:

SR_ldiv:	; N_LDIV@
	pop    cx
	push   cs
	push   cx
	; LDIV@
	xor    cx,cx
	jmp    LSR_01
SR_uldiv:	; N_LUDIV@
	pop    cx
	push   cs
	push   cx
	; F_LUDIV@
	mov    cx,0001
	jmp    LSR_01
SR_lmod:	; N_LMOD@
	pop    cx
	push   cs
	push   cx
	; F_LMOD@
	mov    cx,0002
	jmp    LSR_01
SR_ilmod:	; N_LUMOD@
	pop    cx
	push   cs
	push   cx
	; LUMOD@
	mov    cx,0003
LSR_01:
	push   bp
	push   si
	push   di
	mov    bp,sp
	mov    di,cx
	mov    ax,[bp+0Ah]
	mov    dx,[bp+0Ch]
	mov    bx,[bp+0Eh]
	mov    cx,[bp+10h]
	or     cx,cx
	jne    LSR_02
	or     dx,dx
	je     LSR_10
	or     bx,bx
	je     LSR_10
LSR_02:
	test   di,0001
	jne    LSR_04
	or     dx,dx
	jns    LSR_03
	neg    dx
	neg    ax
	sbb    dx,0000
	or     di,000Ch
LSR_03:
	or     cx,cx
	jns    LSR_04
	neg    cx
	neg    bx
	sbb    cx,0000
	xor    di,0004
LSR_04:
	mov    bp,cx
	mov    cx,0020h
	push   di
	xor    di,di
	xor    si,si
LSR_05:
	shl    ax,1
	rcl    dx,1
	rcl    si,1
	rcl    di,1
	cmp    di,bp
	jb     LSR_07
	ja     LSR_06
	cmp    si,bx
	jb     LSR_07
LSR_06:
	sub    si,bx
	sbb    di,bp
	inc    ax
LSR_07:
	loop   LSR_05
	pop    bx
	test   bx,0002
	je     LSR_08
	mov    ax,si
	mov    dx,di
	shr    bx,1
LSR_08:
	test   bx,0004h
	je     LSR_09
	neg    dx
	neg    ax
	sbb    dx,0000
LSR_09:
	pop    di
	pop    si
	pop    bp
	retf   0008
LSR_10:
	div    bx
	test   di,0002
	je     LSR_11
	xchg   dx,ax
LSR_11:
	xor    dx,dx
	jmp    LSR_09
SR_lshl:	; N_LXLSH@
SR_ulshl:
	; r = a << b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

	mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXLSH@
	cmp    cl,10h
	jnb    LSR_12
	mov    bx,ax
	shl    ax,cl
	shl    dx,cl
	neg    cl
	add    cl,10h
	shr    bx,cl
	or     dx,bx
	pop    cx
	pop    bp
	retf
LSR_12:
	sub    cl,10h
	xchg   dx,ax
	xor    ax,ax
	shl    dx,cl
	pop    cx
	pop    bp
	retf
SR_lshr:	; N_LXRSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXRSH@
	cmp    cl,10h
	jnb    LSR_13
	mov    bx,dx
	shr    ax,cl
	sar    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_13:
	sub    cl,10h
	xchg   dx,ax
	cwd
	sar    ax,cl
	pop    cx
	pop    bp
	retf
SR_ulshr:	; N_LXURSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXURSH@
	cmp    cl,10h
	jnb    LSR_14
	mov    bx,dx
	shr    ax,cl
	shr    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_14:
	sub    cl,10h
	xchg   dx,ax
	xor    dx,dx
	shr    ax,cl
	pop    cx
	pop    bp
	retf
SR_lmul:	; N_LXMUL@
SR_ulmul:
	; r = a * b
	push   bp
	push   si
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx
	push   bx

        mov    bx, [bp+6]	; pop loword(a)
	mov    cx, [bp+8]	; pop hiword(a)
	mov    ax, [bp+10]	; pop loword(b)
	mov    dx, [bp+12]	; pop hiword(b)
	
	xchg   si,ax
	xchg   dx,ax
	test   ax,ax
	je     LSR_15
	mul    bx
LSR_15:
	jcxz   LSR_16
	xchg   cx,ax
	mul    si
	add    ax,cx
LSR_16:
	xchg   si,ax
	mul    bx
	add    dx,si
	pop    bx
	pop    cx
	pop    si
	pop    bp
	ret

; Generated by c86 (BYU-NASM) 5.1 (beta) from clib.c
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
new_line:
	db	13,10,36
	ALIGN	2
signalEOI:
	jmp	L_clib_1
L_clib_2:
	mov	al, 0x20
	out	0x20, al
	mov	sp, bp
	pop	bp
	ret
L_clib_1:
	push	bp
	mov	bp, sp
	jmp	L_clib_2
	ALIGN	2
exit:
	jmp	L_clib_4
L_clib_5:
	mov	ah, 4Ch
	mov	al, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_4:
	push	bp
	mov	bp, sp
	jmp	L_clib_5
	ALIGN	2
print:
	jmp	L_clib_7
L_clib_8:
	mov	ah, 40h
	mov	bx, 1
	mov	cx, [bp+6]
	mov	dx, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_7:
	push	bp
	mov	bp, sp
	jmp	L_clib_8
	ALIGN	2
printChar:
	jmp	L_clib_10
L_clib_11:
	mov	ah, 2
	mov	dl, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_10:
	push	bp
	mov	bp, sp
	jmp	L_clib_11
	ALIGN	2
printNewLine:
	jmp	L_clib_13
L_clib_14:
	mov	ah, 9
	mov	dx, new_line
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_13:
	push	bp
	mov	bp, sp
	jmp	L_clib_14
	ALIGN	2
printString:
	jmp	L_clib_16
L_clib_17:
	xor	si,si
	mov	bx, [bp+4]
	jmp	printString2
	printString1:
	inc	si
	printString2:
	cmp	byte [bx+si],0
	jne	printString1
	mov	dx, bx
	mov	cx, si
	mov	ah, 40h
	mov	bx, 1
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_16:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_clib_17
	ALIGN	2
printInt:
	jmp	L_clib_19
L_clib_20:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	cmp	word [bp+4], 0
	jge	L_clib_21
	mov	byte [bp-10], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	neg	ax
	mov	word [bp+4], ax
L_clib_21:
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_22
	mov	word [bp-4], 1
	jmp	L_clib_23
L_clib_22:
	jmp	L_clib_25
L_clib_24:
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
L_clib_25:
	mov	ax, word [bp+4]
	cwd
	idiv	word [bp-4]
	test	ax, ax
	je	L_clib_24
L_clib_26:
L_clib_23:
	jmp	L_clib_28
L_clib_27:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	ax, dx
	mov	word [bp+4], ax
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
	mov	ax, word [bp-4]
	mov	word [bp-4], ax
L_clib_28:
	cmp	word [bp-4], 0
	jg	L_clib_27
L_clib_29:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_19:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_20
	ALIGN	2
printLong:
	jmp	L_clib_31
L_clib_32:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	cmp	word [bp+6], 0
	jg	L_clib_33
	jl	L_clib_34
	cmp	word [bp+4], 0
	jae	L_clib_33
L_clib_34:
	mov	byte [bp-17], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	neg	ax
	adc	dx, 0
	neg	dx
	mov	word [bp+4], ax
	mov	word [bp+6], dx
L_clib_33:
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_35
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_36
L_clib_35:
	jmp	L_clib_38
L_clib_37:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_38:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_ldiv
	or	dx, ax
	je	L_clib_37
L_clib_39:
L_clib_36:
	jmp	L_clib_41
L_clib_40:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_lmod
	mov	word [bp+4], ax
	mov	word [bp+6], dx
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_41:
	cmp	word [bp-4], 0
	jg	L_clib_40
	jne	L_clib_43
	cmp	word [bp-6], 0
	ja	L_clib_40
L_clib_43:
L_clib_42:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_31:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_32
	ALIGN	2
printUInt:
	jmp	L_clib_45
L_clib_46:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_47
	mov	word [bp-4], 1
	jmp	L_clib_48
L_clib_47:
	jmp	L_clib_50
L_clib_49:
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_50:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	test	ax, ax
	je	L_clib_49
L_clib_51:
L_clib_48:
	jmp	L_clib_53
L_clib_52:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	word [bp+4], dx
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_53:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_clib_52
L_clib_54:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_45:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_46
	ALIGN	2
printULong:
	jmp	L_clib_56
L_clib_57:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_58
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_59
L_clib_58:
	jmp	L_clib_61
L_clib_60:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_61:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	or	dx, ax
	je	L_clib_60
L_clib_62:
L_clib_59:
	jmp	L_clib_64
L_clib_63:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	lea	ax, [bp+4]
	push	ax
	call	SR_asilmod
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_64:
	mov	ax, word [bp-6]
	mov	dx, word [bp-4]
	or	dx, ax
	jne	L_clib_63
L_clib_65:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_56:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_57
	ALIGN	2
printByte:
	jmp	L_clib_67
L_clib_68:
	mov	al, byte [bp+4]
	cbw
	mov	cx, 4
	sar	ax, cl
	and	ax, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_69
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_70
L_clib_69:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_70:
	mov	byte [bp-3], al
	mov	al, byte [bp+4]
	and	al, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_71
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_72
L_clib_71:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_72:
	mov	byte [bp-2], al
	mov	ax, 2
	push	ax
	lea	ax, [bp-3]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_67:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_clib_68
	ALIGN	2
printWord:
	jmp	L_clib_74
L_clib_75:
	mov	word [bp-2], 3
	jmp	L_clib_77
L_clib_76:
	mov	ax, word [bp+4]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_80
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_81
L_clib_80:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_81:
	mov	si, word [bp-2]
	lea	dx, [bp-7]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp+4]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp+4], ax
L_clib_79:
	dec	word [bp-2]
L_clib_77:
	cmp	word [bp-2], 0
	jge	L_clib_76
L_clib_78:
	mov	ax, 4
	push	ax
	lea	ax, [bp-7]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_74:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_clib_75
	ALIGN	2
printDWord:
	jmp	L_clib_83
L_clib_84:
	lea	ax, [bp+4]
	mov	si, ax
	mov	ax, word [si]
	mov	word [bp-6], ax
	lea	ax, [bp+4]
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-8], ax
	mov	word [bp-2], 3
	jmp	L_clib_86
L_clib_85:
	mov	ax, word [bp-6]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_89
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_90
L_clib_89:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_90:
	mov	dx, word [bp-2]
	add	dx, 4
	mov	si, dx
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-6]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-6], ax
	mov	ax, word [bp-8]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_91
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_92
L_clib_91:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_92:
	mov	si, word [bp-2]
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-8]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-8], ax
L_clib_88:
	dec	word [bp-2]
L_clib_86:
	cmp	word [bp-2], 0
	jge	L_clib_85
L_clib_87:
	mov	ax, 8
	push	ax
	lea	ax, [bp-16]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_83:
	push	bp
	mov	bp, sp
	sub	sp, 16
	jmp	L_clib_84

reset:
	push ax
	push bx
	push cx
	push dx
	push si
	push di
	push bp
	push es
	push ds
	
	sti
	call reset_handler
	cli

	mov	al, 0x20	; Load nonspecific EOI value (0x20) into register al
	out	0x20, al	; Write EOI to PIC (port 0x20)
	
	pop ds
	pop es
	pop bp
	pop di
	pop si
	pop dx
	pop cx
	pop bx
	pop ax
	iret

tick:
	push ax
	push bx
	push cx
	push dx
	push si
	push di
	push bp
	push es
	push ds
	
	
	sti
	call tick_handler
	cli	
	
	mov	al, 0x20	; Load nonspecific EOI value (0x20) into register al
	out	0x20, al	; Write EOI to PIC (port 0x20)
		
	pop ds
	pop es
	pop bp
	pop di
	pop si
	pop dx
	pop cx
	pop bx
	pop ax
	iret
	
keyboard:
	push ax
	push bx
	push cx
	push dx
	push si
	push di
	push bp
	push es
	push ds
	
	sti
	call keyboard_handler
	cli	
	
	mov	al, 0x20	; Load nonspecific EOI value (0x20) into register al
	out	0x20, al	; Write EOI to PIC (port 0x20)	
	
	
	pop ds
	pop es
	pop bp
	pop di
	pop si
	pop dx
	pop cx
	pop bx
	pop ax
	iret
	
YKDispatcher:

		cli
		push 	bp
		mov		bp, sp		

		mov		bx, [bp+4]	;Obtain stack pointer from TCB
		mov		sp, [bx+4]	;Load stack pointer into SP

		pop		bp
		pop		es
		pop		ds
		pop		si
		pop		di
		pop		dx
		pop		cx
		pop		bx
		pop		ax

		iret

; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
counter:
	DW	0
	ALIGN	2
reset_handler:
	; >>>>> Line:	7
	; >>>>> void reset_handler(){ 
	jmp	L_myinth_1
L_myinth_2:
	; >>>>> Line:	8
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_1:
	push	bp
	mov	bp, sp
	jmp	L_myinth_2
L_myinth_4:
	DB	"TICK ",0
	ALIGN	2
tick_handler:
	; >>>>> Line:	11
	; >>>>> void tick_handler(){ 
	jmp	L_myinth_5
L_myinth_6:
	; >>>>> Line:	12
	; >>>>> counter++; 
	inc	word [counter]
	; >>>>> Line:	13
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	14
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	15
	; >>>>> printString("TICK "); 
	mov	ax, L_myinth_4
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	16
	; >>>>> printInt(counter); 
	push	word [counter]
	call	printInt
	add	sp, 2
	; >>>>> Line:	17
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	18
	; >>>>> printNewLine(); 
	call	printNewLine
	mov	sp, bp
	pop	bp
	ret
L_myinth_5:
	push	bp
	mov	bp, sp
	jmp	L_myinth_6
L_myinth_11:
	DB	" IGNORED",0
L_myinth_10:
	DB	"KEYPRESS ",0
L_myinth_9:
	DB	"DELAY COMPLETE",0
L_myinth_8:
	DB	"DELAY KEY PRESSED",0
	ALIGN	2
keyboard_handler:
	; >>>>> Line:	21
	; >>>>> void keyboard_handler(){ 
	jmp	L_myinth_12
L_myinth_13:
	; >>>>> Line:	25
	; >>>>> if(kb == 'd'){ 
	mov	al, byte [KeyBuffer]
	mov	byte [bp-3], al
	; >>>>> Line:	25
	; >>>>> if(kb == 'd'){ 
	cmp	byte [bp-3], 100
	jne	L_myinth_14
	; >>>>> Line:	26
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	27
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	28
	; >>>>> printString("DELAY KEY PRESSED"); 
	mov	ax, L_myinth_8
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	29
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	30
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	33
	; >>>>> for(i = 0; i < 5000; i++){ 
	mov	word [bp-2], 0
	jmp	L_myinth_16
L_myinth_15:
L_myinth_18:
	; >>>>> Line:	35
	; >>>>> } 
	inc	word [bp-2]
L_myinth_16:
	cmp	word [bp-2], 5000
	jl	L_myinth_15
L_myinth_17:
	; >>>>> Line:	37
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	38
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	39
	; >>>>> printString("DELAY COMPLETE"); 
	mov	ax, L_myinth_9
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	40
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	41
	; >>>>> printNewLine(); 
	call	printNewLine
	jmp	L_myinth_19
L_myinth_14:
	; >>>>> Line:	45
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	46
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	47
	; >>>>> printString("KEYPRESS "); 
	mov	ax, L_myinth_10
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	48
	; >>>>> printChar('('); 
	mov	al, 40
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	49
	; >>>>> printChar(kb); 
	push	word [bp-3]
	call	printChar
	add	sp, 2
	; >>>>> Line:	50
	; >>>>> printChar(')'); 
	mov	al, 41
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	51
	; >>>>> printString(" IGNORED"); 
	mov	ax, L_myinth_11
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	52
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	53
	; >>>>> printNewLine(); 
	call	printNewLine
L_myinth_19:
	mov	sp, bp
	pop	bp
	ret
L_myinth_12:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_myinth_13
; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
L_yakc_4:
	DW	0
L_yakc_6:
	DW	0
L_yakc_7:
	DW	0
	ALIGN	2
getYKCtxSwCount:
	; >>>>> Line:	16
	; >>>>> unsigned int getYKCtxSwCount() { 
	jmp	L_yakc_8
L_yakc_9:
	; >>>>> Line:	17
	; >>>>> return YKCtxSwCount; 
	mov	ax, word [L_yakc_6]
L_yakc_10:
	mov	sp, bp
	pop	bp
	ret
L_yakc_8:
	push	bp
	mov	bp, sp
	jmp	L_yakc_9
	ALIGN	2
YKInitialize:
	; >>>>> Line:	20
	; >>>>>  
	jmp	L_yakc_12
L_yakc_13:
	; >>>>> Line:	21
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	24
	; >>>>> initializeReadyQueue(); 
	call	initializeReadyQueue
	; >>>>> Line:	25
	; >>>>> initializeDelayQueue(); 
	call	initializeDelayQueue
	; >>>>> Line:	26
	; >>>>> taskBlock.nextFreeTCB = 0; 
	mov	word [(56+L_yakc_1)], 0
	; >>>>> Line:	28
	; >>>>> YKNewTask(YKIdleTask, &idleStack[3], 100); 
	mov	al, 100
	push	ax
	mov	ax, (L_yakc_2+6)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	30
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_12:
	push	bp
	mov	bp, sp
	jmp	L_yakc_13
	ALIGN	2
YKEnterMutex:
	; >>>>> Line:	33
	; >>>>> void YKEnterMutex(void){ 
	jmp	L_yakc_15
L_yakc_16:
	; >>>>> Line:	34
	; >>>>> asm("cli"); 
	cli
	mov	sp, bp
	pop	bp
	ret
L_yakc_15:
	push	bp
	mov	bp, sp
	jmp	L_yakc_16
	ALIGN	2
YKExitMutex:
	; >>>>> Line:	37
	; >>>>> void YKExitMutex(void){ 
	jmp	L_yakc_18
L_yakc_19:
	; >>>>> Line:	38
	; >>>>> asm("sti"); 
	sti
	mov	sp, bp
	pop	bp
	ret
L_yakc_18:
	push	bp
	mov	bp, sp
	jmp	L_yakc_19
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	41
	; >>>>> void YKIdleTask(void){ 
	jmp	L_yakc_21
L_yakc_22:
	; >>>>> Line:	44
	; >>>>> while(1){ 
	jmp	L_yakc_24
L_yakc_23:
	; >>>>> Line:	45
	; >>>>> dummy++; 
	inc	word [bp-2]
	; >>>>> Line:	46
	; >>>>> dummy--; 
	dec	word [bp-2]
	; >>>>> Line:	47
	; >>>>> YKIdleCount++; 
	inc	word [L_yakc_7]
L_yakc_24:
	jmp	L_yakc_23
L_yakc_25:
	mov	sp, bp
	pop	bp
	ret
L_yakc_21:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_22
	ALIGN	2
YKNewTask:
	; >>>>> Line:	51
	; >>>>> void YKNewTask(void (*task)(void), void *taskStack, unsigned char priority){ 
	jmp	L_yakc_27
L_yakc_28:
	; >>>>> Line:	54
	; >>>>> newTCB = getNewTCB(); 
	call	getNewTCB
	mov	word [bp-2], ax
	; >>>>> Line:	55
	; >>>>> if(newTCB == 0) { 
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_29
	; >>>>> Line:	56
	; >>>>> exit(-1); 
	mov	ax, -1
	push	ax
	call	exit
	add	sp, 2
L_yakc_29:
	; >>>>> Line:	60
	; >>>>> TASK_ID+ 
	inc	word [L_yakc_4]
	; >>>>> Line:	61
	; >>>>> newTCB->tid = TASK_ID; 
	mov	si, word [bp-2]
	mov	ax, word [L_yakc_4]
	mov	word [si], ax
	; >>>>> Line:	62
	; >>>>> newTCB->priority = priority; 
	mov	si, word [bp-2]
	add	si, 2
	mov	al, byte [bp+8]
	mov	byte [si], al
	; >>>>> Line:	63
	; >>>>> newTCB->stackPointer = ((void*)((int*) taskStack - 12)); 
	mov	ax, word [bp+6]
	sub	ax, 24
	mov	si, word [bp-2]
	add	si, 4
	mov	word [si], ax
	; >>>>> Line:	64
	; >>>>> newTCB->state = T_READY; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 1
	; >>>>> Line:	65
	; >>>>> newTCB->delayCount = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	66
	; >>>>> newTCB->next = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	67
	; >>>>> newTCB->prev = 0; 
	mov	si, word [bp-2]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	70
	; >>>>> asm("push bx"); 
	push bx
	; >>>>> Line:	71
	; >>>>> asm("push cx"); 
	push cx
	; >>>>> Line:	72
	; >>>>> asm("mov bx, [bp+6]"); 
	mov bx, [bp+6]
	; >>>>> Line:	73
	; >>>>> asm("mov cx, [bp+4]"); 
	mov cx, [bp+4]
	; >>>>> Line:	74
	; >>>>> asm("mov [bx-2], word 0x0200"); 
	mov [bx-2], word 0x0200
	; >>>>> Line:	75
	; >>>>> asm("mov [bx-4], word 0x0"); 
	mov [bx-4], word 0x0
	; >>>>> Line:	76
	; >>>>> asm("mov [bx-6], cx"); 
	mov [bx-6], cx
	; >>>>> Line:	77
	; >>>>> asm("pop cx"); 
	pop cx
	; >>>>> Line:	78
	; >>>>> asm("pop bx"); 
	pop bx
	; >>>>> Line:	81
	; >>>>> insertReadyQueue(newTCB); 
	push	word [bp-2]
	call	insertReadyQueue
	add	sp, 2
	; >>>>> Line:	82
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_30:
	; >>>>> Line:	83
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_27:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_28
	ALIGN	2
YKRun:
	; >>>>> Line:	86
	; >>>>> void YKRun(void){ 
	jmp	L_yakc_32
L_yakc_33:
	; >>>>> Line:	87
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	88
	; >>>>> ask = &taskB 
	mov	word [L_yakc_3], 1
	; >>>>> Line:	89
	; >>>>> YKScheduler(); 
	call	YKScheduler
	; >>>>> Line:	90
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_32:
	push	bp
	mov	bp, sp
	jmp	L_yakc_33
	ALIGN	2
YKScheduler:
	; >>>>> Line:	93
	; >>>>> void YKScheduler(void){ 
	jmp	L_yakc_35
L_yakc_36:
	; >>>>> Line:	96
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	97
	; >>>>> if(kernelState == K_BLOCKED) { 
	mov	ax, word [L_yakc_3]
	test	ax, ax
	jne	L_yakc_37
	; >>>>> Line:	98
	; >>>>> return; 
	jmp	L_yakc_38
L_yakc_37:
	; >>>>> Line:	100
	; >>>>> newTask = peekReadyQueue(); 
	call	peekReadyQueue
	mov	word [bp-2], ax
	; >>>>> Line:	101
	; >>>>> if(newTask == 0) { 
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_39
	; >>>>> Line:	102
	; >>>>> exit(-2); 
	mov	ax, -2
	push	ax
	call	exit
	add	sp, 2
L_yakc_39:
	; >>>>> Line:	104
	; >>>>> if(newTask != currentTask) { 
	mov	ax, word [L_yakc_5]
	cmp	ax, word [bp-2]
	je	L_yakc_40
	; >>>>> Line:	105
	; >>>>> currentTask->state = T_READY; 
	mov	si, word [L_yakc_5]
	add	si, 6
	mov	word [si], 1
	; >>>>> Line:	106
	; >>>>> currentTask = newTask; 
	mov	ax, word [bp-2]
	mov	word [L_yakc_5], ax
	; >>>>> Line:	107
	; >>>>> currentTask->state = T_RUNNING; 
	mov	si, word [L_yakc_5]
	add	si, 6
	mov	word [si], 2
	; >>>>> Line:	108
	; >>>>> YKCtxSwCount++; 
	inc	word [L_yakc_6]
	; >>>>> Line:	109
	; >>>>> YKDispatcher(); 
	call	YKDispatcher
L_yakc_40:
	; >>>>> Line:	111
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_38:
	; >>>>> Line:	112
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_35:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_36
	ALIGN	2
getNewTCB:
	; >>>>> Line:	134
	; >>>>> TCB* getNewTCB(void) { 
	jmp	L_yakc_42
L_yakc_43:
	; >>>>> Line:	136
	; >>>>> if (taskBlock.nextFreeTCB < 3 + 1) { 
	cmp	word [(56+L_yakc_1)], 4
	jae	L_yakc_44
	; >>>>> Line:	137
	; >>>>> task = &taskB 
	mov	ax, word [(56+L_yakc_1)]
	mov	cx, 14
	imul	cx
	add	ax, L_yakc_1
	mov	word [bp-2], ax
	; >>>>> Line:	138
	; >>>>> taskBlock.nextFreeTCB++; 
	inc	word [(56+L_yakc_1)]
	; >>>>> Line:	139
	; >>>>> return task; 
	mov	ax, word [bp-2]
	jmp	L_yakc_45
	jmp	L_yakc_46
L_yakc_44:
	; >>>>> Line:	141
	; >>>>> return 0; 
	xor	ax, ax
L_yakc_46:
L_yakc_45:
	mov	sp, bp
	pop	bp
	ret
L_yakc_42:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_43
	ALIGN	2
readyQueue:
	TIMES	6 db 0
delayQueue:
	TIMES	4 db 0
L_yakc_1:
	TIMES	58 db 0
L_yakc_2:
	TIMES	6 db 0
L_yakc_3:
	TIMES	2 db 0
L_yakc_5:
	TIMES	2 db 0
; Generated by c86 (BYU-NASM) 5.1 (beta) from ReadyQueue.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
initializeReadyQueue:
	; >>>>> Line:	7
	; >>>>> void initializeReadyQueue() { 
	jmp	L_ReadyQueue_1
L_ReadyQueue_2:
	; >>>>> Line:	8
	; >>>>> readyQueue.size = 0; 
	mov	word [(4+readyQueue)], 0
	; >>>>> Line:	9
	; >>>>> readyQueue.head = 
	mov	word [readyQueue], 0
	; >>>>> Line:	10
	; >>>>> readyQueue.tail = 0; 
	mov	word [(2+readyQueue)], 0
	mov	sp, bp
	pop	bp
	ret
L_ReadyQueue_1:
	push	bp
	mov	bp, sp
	jmp	L_ReadyQueue_2
	ALIGN	2
insertReadyQueue:
	; >>>>> Line:	13
	; >>>>> void insertReadyQueue(TCB* tcb) { 
	jmp	L_ReadyQueue_4
L_ReadyQueue_5:
	; >>>>> Line:	17
	; >>>>> if(tcb == 0) return; 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_ReadyQueue_6
	; >>>>> Line:	17
	; >>>>> if(tcb == 0) return; 
	jmp	L_ReadyQueue_7
L_ReadyQueue_6:
	; >>>>> Line:	20
	; >>>>> if (readyQueue.size == 0) { 
	mov	ax, word [(4+readyQueue)]
	test	ax, ax
	jne	L_ReadyQueue_8
	; >>>>> Line:	21
	; >>>>> readyQueue.head = tcb; 
	mov	ax, word [bp+4]
	mov	word [readyQueue], ax
	; >>>>> Line:	22
	; >>>>> readyQueue.tail = tcb; 
	mov	word [(2+readyQueue)], ax
	; >>>>> Line:	23
	; >>>>> tcb->next = 0; 
	mov	si, word [bp+4]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	24
	; >>>>> tcb->prev = 0; 
	mov	si, word [bp+4]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	25
	; >>>>> readyQueue.size = 1; 
	mov	word [(4+readyQueue)], 1
	; >>>>> Line:	26
	; >>>>> return; 
	jmp	L_ReadyQueue_7
L_ReadyQueue_8:
	; >>>>> Line:	30
	; >>>>> if (readyQueue.size == 1) { 
	cmp	word [(4+readyQueue)], 1
	jne	L_ReadyQueue_9
	; >>>>> Line:	31
	; >>>>> if (readyQueue.head->priority < tcb->priority) { 
	mov	si, word [readyQueue]
	add	si, 2
	mov	di, word [bp+4]
	add	di, 2
	mov	al, byte [di]
	cmp	al, byte [si]
	jbe	L_ReadyQueue_10
	; >>>>> Line:	32
	; >>>>> readyQueue.head->next = tcb; 
	mov	si, word [readyQueue]
	add	si, 10
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	33
	; >>>>> tcb->prev = readyQueue.head; 
	mov	si, word [bp+4]
	add	si, 12
	mov	ax, word [readyQueue]
	mov	word [si], ax
	; >>>>> Line:	34
	; >>>>> tcb->next = 0; 
	mov	si, word [bp+4]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	35
	; >>>>> readyQueue.tail = tcb; 
	mov	ax, word [bp+4]
	mov	word [(2+readyQueue)], ax
	; >>>>> Line:	36
	; >>>>> readyQueue.size++; 
	inc	word [(4+readyQueue)]
	; >>>>> Line:	37
	; >>>>> return; 
	jmp	L_ReadyQueue_7
	jmp	L_ReadyQueue_11
L_ReadyQueue_10:
	; >>>>> Line:	39
	; >>>>> tcb->next = readyQueue.he 
	mov	si, word [bp+4]
	add	si, 10
	mov	ax, word [readyQueue]
	mov	word [si], ax
	; >>>>> Line:	40
	; >>>>> tcb->prev = 0; 
	mov	si, word [bp+4]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	41
	; >>>>> readyQueue.tail->prev = tcb; 
	mov	si, word [(2+readyQueue)]
	add	si, 12
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	42
	; >>>>> readyQueue.head = tcb; 
	mov	ax, word [bp+4]
	mov	word [readyQueue], ax
	; >>>>> Line:	43
	; >>>>> readyQueue.size++; 
	inc	word [(4+readyQueue)]
	; >>>>> Line:	44
	; >>>>> return; 
	jmp	L_ReadyQueue_7
L_ReadyQueue_11:
L_ReadyQueue_9:
	; >>>>> Line:	49
	; >>>>> temp = readyQueue.head; 
	mov	ax, word [readyQueue]
	mov	word [bp-2], ax
	; >>>>> Line:	50
	; >>>>> while (temp != 0) { 
	jmp	L_ReadyQueue_13
L_ReadyQueue_12:
	; >>>>> Line:	51
	; >>>>> if (temp->priority > tcb->priority) { 
	mov	si, word [bp-2]
	add	si, 2
	mov	di, word [bp+4]
	add	di, 2
	mov	al, byte [di]
	cmp	al, byte [si]
	jae	L_ReadyQueue_15
	; >>>>> Line:	52
	; >>>>> tcb->next = temp; 
	mov	si, word [bp+4]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	53
	; >>>>> tcb->prev = temp->prev; 
	mov	si, word [bp-2]
	add	si, 12
	mov	di, word [bp+4]
	add	di, 12
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	54
	; >>>>> temp->prev = tcb; 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	55
	; >>>>> if (temp == readyQueue.head) readyQueue.head = tcb; 
	mov	ax, word [readyQueue]
	cmp	ax, word [bp-2]
	jne	L_ReadyQueue_16
	; >>>>> Line:	55
	; >>>>> if (temp == readyQueue.head) readyQueue.head = tcb; 
	mov	ax, word [bp+4]
	mov	word [readyQueue], ax
L_ReadyQueue_16:
	; >>>>> Line:	56
	; >>>>> readyQueue.size++; 
	inc	word [(4+readyQueue)]
	; >>>>> Line:	57
	; >>>>> return; 
	jmp	L_ReadyQueue_7
L_ReadyQueue_15:
	; >>>>> Line:	59
	; >>>>> temp = temp->next; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-2], ax
L_ReadyQueue_13:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_ReadyQueue_12
L_ReadyQueue_14:
	; >>>>> Line:	63
	; >>>>> readyQueue.tail->next = tcb; 
	mov	si, word [(2+readyQueue)]
	add	si, 10
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	64
	; >>>>> tcb->prev = readyQueue.tail; 
	mov	si, word [bp+4]
	add	si, 12
	mov	ax, word [(2+readyQueue)]
	mov	word [si], ax
	; >>>>> Line:	65
	; >>>>> readyQueue.tail = tcb; 
	mov	ax, word [bp+4]
	mov	word [(2+readyQueue)], ax
	; >>>>> Line:	66
	; >>>>> tcb->next = 0; 
	mov	si, word [bp+4]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	67
	; >>>>> readyQueue.size+ 
	inc	word [(4+readyQueue)]
L_ReadyQueue_7:
	; >>>>> Line:	68
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_ReadyQueue_4:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_ReadyQueue_5
	ALIGN	2
peekReadyQueue:
	; >>>>> Line:	72
	; >>>>> TCB* peekReadyQueue() { 
	jmp	L_ReadyQueue_18
L_ReadyQueue_19:
	; >>>>> Line:	73
	; >>>>> if (readyQueue.size == 0) { 
	mov	ax, word [(4+readyQueue)]
	test	ax, ax
	jne	L_ReadyQueue_20
	; >>>>> Line:	74
	; >>>>> return 0; 
	xor	ax, ax
	jmp	L_ReadyQueue_21
	jmp	L_ReadyQueue_22
L_ReadyQueue_20:
	; >>>>> Line:	76
	; >>>>> return readyQueue.head; 
	mov	ax, word [readyQueue]
L_ReadyQueue_22:
L_ReadyQueue_21:
	mov	sp, bp
	pop	bp
	ret
L_ReadyQueue_18:
	push	bp
	mov	bp, sp
	jmp	L_ReadyQueue_19
	ALIGN	2
removeReadyQueue:
	; >>>>> Line:	80
	; >>>>> TCB* removeReadyQueue() { 
	jmp	L_ReadyQueue_24
L_ReadyQueue_25:
	; >>>>> Line:	84
	; >>>>> if (readyQueue.size == 0) { 
	mov	ax, word [(4+readyQueue)]
	test	ax, ax
	jne	L_ReadyQueue_26
	; >>>>> Line:	85
	; >>>>> retValue = readyQueue.head; 
	mov	ax, word [readyQueue]
	mov	word [bp-2], ax
	; >>>>> Line:	86
	; >>>>> readyQueue.size--; 
	dec	word [(4+readyQueue)]
	; >>>>> Line:	87
	; >>>>> readyQueue.head = 0; 
	mov	word [readyQueue], 0
	; >>>>> Line:	88
	; >>>>> readyQueue.tail = 0; 
	mov	word [(2+readyQueue)], 0
	; >>>>> Line:	89
	; >>>>> return retValue; 
	mov	ax, word [bp-2]
	jmp	L_ReadyQueue_27
L_ReadyQueue_26:
	; >>>>> Line:	92
	; >>>>> retValue = readyQueue.head; 
	mov	ax, word [readyQueue]
	mov	word [bp-2], ax
	; >>>>> Line:	93
	; >>>>> readyQueue.head = readyQueue.head->next; 
	mov	si, word [readyQueue]
	add	si, 10
	mov	ax, word [si]
	mov	word [readyQueue], ax
	; >>>>> Line:	94
	; >>>>> readyQueue.size--; 
	dec	word [(4+readyQueue)]
	; >>>>> Line:	95
	; >>>>> return retValue; 
	mov	ax, word [bp-2]
L_ReadyQueue_27:
	mov	sp, bp
	pop	bp
	ret
L_ReadyQueue_24:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_ReadyQueue_25
; Generated by c86 (BYU-NASM) 5.1 (beta) from DelayQueue.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
initializeDelayQueue:
	; >>>>> Line:	8
	; >>>>> void initializeDelayQueue() { 
	jmp	L_DelayQueue_1
L_DelayQueue_2:
	; >>>>> Line:	9
	; >>>>> delayQueue.size = 0; 
	mov	word [(2+delayQueue)], 0
	; >>>>> Line:	10
	; >>>>> delayQueue.head = 0; 
	mov	word [delayQueue], 0
	mov	sp, bp
	pop	bp
	ret
L_DelayQueue_1:
	push	bp
	mov	bp, sp
	jmp	L_DelayQueue_2
	ALIGN	2
tickClock:
	; >>>>> Line:	13
	; >>>>> void tickClock() { 
	jmp	L_DelayQueue_4
L_DelayQueue_5:
	; >>>>> Line:	18
	; >>>>> if (delayQueue.size == 0) return; 
	mov	ax, word [(2+delayQueue)]
	test	ax, ax
	jne	L_DelayQueue_6
	; >>>>> Line:	18
	; >>>>> if (delayQueue.size == 0) return; 
	jmp	L_DelayQueue_7
L_DelayQueue_6:
	; >>>>> Line:	21
	; >>>>> current = delayQueue.head; 
	mov	ax, word [delayQueue]
	mov	word [bp-2], ax
	; >>>>> Line:	22
	; >>>>> while (current != 0) { 
	jmp	L_DelayQueue_9
L_DelayQueue_8:
	; >>>>> Line:	23
	; >>>>> rent != 0) { 
	mov	si, word [bp-2]
	add	si, 8
	dec	word [si]
	; >>>>> Line:	24
	; >>>>> temp = current; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
	; >>>>> Line:	25
	; >>>>> if (temp->delayCount == 0) { 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	jne	L_DelayQueue_11
	; >>>>> Line:	26
	; >>>>> removeDelayQueue(temp); 
	push	word [bp-4]
	call	removeDelayQueue
	add	sp, 2
L_DelayQueue_11:
	; >>>>> Line:	28
	; >>>>> current = current->next; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-2], ax
L_DelayQueue_9:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_DelayQueue_8
L_DelayQueue_10:
L_DelayQueue_7:
	mov	sp, bp
	pop	bp
	ret
L_DelayQueue_4:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_DelayQueue_5
	ALIGN	2
insertDelayQueue:
	; >>>>> Line:	33
	; >>>>> void insertDelayQueue(TCB* tcb) { 
	jmp	L_DelayQueue_13
L_DelayQueue_14:
	; >>>>> Line:	38
	; >>>>> if (tcb == 0) return; 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_DelayQueue_15
	; >>>>> Line:	38
	; >>>>> if (tcb == 0) return; 
	jmp	L_DelayQueue_16
L_DelayQueue_15:
	; >>>>> Line:	41
	; >>>>> if (delayQueue.size == 0) { 
	mov	ax, word [(2+delayQueue)]
	test	ax, ax
	jne	L_DelayQueue_17
	; >>>>> Line:	42
	; >>>>> delayQueue.head = tcb; 
	mov	ax, word [bp+4]
	mov	word [delayQueue], ax
	; >>>>> Line:	43
	; >>>>> tcb->next = 0; 
	mov	si, word [bp+4]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	44
	; >>>>> tcb->prev = 0; 
	mov	si, word [bp+4]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	45
	; >>>>> delayQueue.size++; 
	inc	word [(2+delayQueue)]
	; >>>>> Line:	46
	; >>>>> return; 
	jmp	L_DelayQueue_16
L_DelayQueue_17:
	; >>>>> Line:	50
	; >>>>> current = delayQueue.head; 
	mov	ax, word [delayQueue]
	mov	word [bp-2], ax
	; >>>>> Line:	51
	; >>>>> sumCount = 0; 
	mov	word [bp-4], 0
	; >>>>> Line:	52
	; >>>>> while (current != 0) { 
	jmp	L_DelayQueue_19
L_DelayQueue_18:
	; >>>>> Line:	53
	; >>>>>  
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	add	word [bp-4], ax
	; >>>>> Line:	54
	; >>>>> if (tcb->delayCount < sumCount) { 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [bp-4]
	cmp	ax, word [si]
	jbe	L_DelayQueue_21
	; >>>>> Line:	55
	; >>>>> tcb->prev = current->prev; 
	mov	si, word [bp-2]
	add	si, 12
	mov	di, word [bp+4]
	add	di, 12
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	56
	; >>>>> tcb->next = current; 
	mov	si, word [bp+4]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	57
	; >>>>> if (current == delayQueue.head) { 
	mov	ax, word [delayQueue]
	cmp	ax, word [bp-2]
	jne	L_DelayQueue_22
	; >>>>> Line:	58
	; >>>>> delayQueue.head = tcb; 
	mov	ax, word [bp+4]
	mov	word [delayQueue], ax
	; >>>>> Line:	59
	; >>>>> current->prev->next = tcb; 
	mov	si, word [bp-2]
	add	si, 12
	mov	si, word [si]
	add	si, 10
	mov	word [si], ax
L_DelayQueue_22:
	; >>>>> Line:	61
	; >>>>> current->prev = tcb; 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	62
	; >>>>> delayQueue.size++; 
	inc	word [(2+delayQueue)]
	; >>>>> Line:	63
	; >>>>> tcb->delayCount = tcb->delayCount - sumCount; 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	sub	ax, word [bp-4]
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], ax
	; >>>>> Line:	64
	; >>>>> return; 
	jmp	L_DelayQueue_16
L_DelayQueue_21:
	; >>>>> Line:	66
	; >>>>> if (current->next == 0) { 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_DelayQueue_23
	; >>>>> Line:	67
	; >>>>> current->next = tcb; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	68
	; >>>>> tcb->prev = current; 
	mov	si, word [bp+4]
	add	si, 12
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	69
	; >>>>> tcb->next = 0; 
	mov	si, word [bp+4]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	70
	; >>>>> delayQueue.size++; 
	inc	word [(2+delayQueue)]
	; >>>>> Line:	71
	; >>>>> tcb->delayCount = tcb->delayCount - sumCount; 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	sub	ax, word [bp-4]
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], ax
	; >>>>> Line:	72
	; >>>>> return; 
	jmp	L_DelayQueue_16
L_DelayQueue_23:
	; >>>>> Line:	74
	; >>>>> current = current->next; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-2], ax
L_DelayQueue_19:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_DelayQueue_18
L_DelayQueue_20:
L_DelayQueue_16:
	mov	sp, bp
	pop	bp
	ret
L_DelayQueue_13:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_DelayQueue_14
	ALIGN	2
removeDelayQueue:
	; >>>>> Line:	79
	; >>>>> void removeDelayQueue(TCB* tcb) { 
	jmp	L_DelayQueue_25
L_DelayQueue_26:
	; >>>>> Line:	84
	; >>>>> if (tcb == 0) return; 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_DelayQueue_27
	; >>>>> Line:	84
	; >>>>> if (tcb == 0) return; 
	jmp	L_DelayQueue_28
L_DelayQueue_27:
	; >>>>> Line:	86
	; >>>>> current = delayQueue.head; 
	mov	ax, word [delayQueue]
	mov	word [bp-2], ax
	; >>>>> Line:	87
	; >>>>> while (current != 0) { 
	jmp	L_DelayQueue_30
L_DelayQueue_29:
	; >>>>> Line:	88
	; >>>>> if (current->priority = tcb->priority) { 
	mov	si, word [bp+4]
	add	si, 2
	mov	di, word [bp-2]
	add	di, 2
	mov	ax, word [si]
	mov	word [di], ax
	test	al, al
	je	L_DelayQueue_32
	; >>>>> Line:	89
	; >>>>> if (current == delayQueue.head) { 
	mov	ax, word [delayQueue]
	cmp	ax, word [bp-2]
	jne	L_DelayQueue_33
	; >>>>> Line:	90
	; >>>>> temp = current; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
	; >>>>> Line:	91
	; >>>>> { 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	92
	; >>>>> delayQueue.head = temp->next; 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	mov	word [delayQueue], ax
	; >>>>> Line:	93
	; >>>>> temp->next->prev = 0; 
	mov	si, word [bp-4]
	add	si, 10
	mov	si, word [si]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	94
	; >>>>> delayQueue.size--; 
	dec	word [(2+delayQueue)]
	; >>>>> Line:	95
	; >>>>> temp->next = 0; 
	mov	si, word [bp-4]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	96
	; >>>>> temp->prev = 0; 
	mov	si, word [bp-4]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	97
	; >>>>> insertReadyQueue(temp); 
	push	word [bp-4]
	call	insertReadyQueue
	add	sp, 2
	jmp	L_DelayQueue_34
L_DelayQueue_33:
	; >>>>> Line:	98
	; >>>>> } else if (current->next == 0) { 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_DelayQueue_35
	; >>>>> Line:	99
	; >>>>> temp = current; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
	; >>>>> Line:	100
	; >>>>> current = current->next; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	101
	; >>>>> temp->prev->next = 0; 
	mov	si, word [bp-4]
	add	si, 12
	mov	si, word [si]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	102
	; >>>>> delayQueue.size--; 
	dec	word [(2+delayQueue)]
	; >>>>> Line:	103
	; >>>>> insertReadyQueue(temp); 
	push	word [bp-4]
	call	insertReadyQueue
	add	sp, 2
	jmp	L_DelayQueue_36
L_DelayQueue_35:
	; >>>>> Line:	105
	; >>>>>  
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
	; >>>>> Line:	106
	; >>>>> current = current->next; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	107
	; >>>>> temp->prev->next = temp->next; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 12
	mov	di, word [di]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	108
	; >>>>> temp->next->prev = temp->prev; 
	mov	si, word [bp-4]
	add	si, 12
	mov	di, word [bp-4]
	add	di, 10
	mov	di, word [di]
	add	di, 12
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	109
	; >>>>> temp->next = 0; 
	mov	si, word [bp-4]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	110
	; >>>>> temp->prev = 0; 
	mov	si, word [bp-4]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	111
	; >>>>> delayQueue.size--; 
	dec	word [(2+delayQueue)]
	; >>>>> Line:	112
	; >>>>> insertReadyQueue(temp); 
	push	word [bp-4]
	call	insertReadyQueue
	add	sp, 2
L_DelayQueue_36:
L_DelayQueue_34:
L_DelayQueue_32:
L_DelayQueue_30:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_DelayQueue_29
L_DelayQueue_31:
L_DelayQueue_28:
	mov	sp, bp
	pop	bp
	ret
L_DelayQueue_25:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_DelayQueue_26
; Generated by c86 (BYU-NASM) 5.1 (beta) from lab4b_app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_lab4b_app_2:
	DB	"Starting kernel...",0xA,0
L_lab4b_app_1:
	DB	"Creating task A...",0xA,0
	ALIGN	2
main:
	; >>>>> Line:	23
	; >>>>> { 
	jmp	L_lab4b_app_3
L_lab4b_app_4:
	; >>>>> Line:	24
	; >>>>> YKInitialize(); 
	call	YKInitialize
	; >>>>> Line:	26
	; >>>>> printString("Creating task A...\n"); 
	mov	ax, L_lab4b_app_1
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	27
	; >>>>> YKNewTask(ATask, (void *)&AStk[256], 5); 
	mov	al, 5
	push	ax
	mov	ax, (AStk+512)
	push	ax
	mov	ax, ATask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	29
	; >>>>> printString("Starting kernel...\n"); 
	mov	ax, L_lab4b_app_2
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	30
	; >>>>> YKRun(); 
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_lab4b_app_3:
	push	bp
	mov	bp, sp
	jmp	L_lab4b_app_4
L_lab4b_app_9:
	DB	"Task A is still running! Oh no! Task A was supposed to stop.",0xA,0
L_lab4b_app_8:
	DB	"Creating task C...",0xA,0
L_lab4b_app_7:
	DB	"Creating low priority task B...",0xA,0
L_lab4b_app_6:
	DB	"Task A started!",0xA,0
	ALIGN	2
ATask:
	; >>>>> Line:	34
	; >>>>> { 
	jmp	L_lab4b_app_10
L_lab4b_app_11:
	; >>>>> Line:	35
	; >>>>> printString("Task A started!\n") 
	mov	ax, L_lab4b_app_6
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	37
	; >>>>> printString("Creating low priority task B...\n"); 
	mov	ax, L_lab4b_app_7
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	38
	; >>>>> YKNewTask(BTask, (void *)&BStk[256], 7); 
	mov	al, 7
	push	ax
	mov	ax, (BStk+512)
	push	ax
	mov	ax, BTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	40
	; >>>>> printString("Creating task C...\n"); 
	mov	ax, L_lab4b_app_8
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	41
	; >>>>> YKNewTask(CTask, (void *)&CStk[256], 2); 
	mov	al, 2
	push	ax
	mov	ax, (CStk+512)
	push	ax
	mov	ax, CTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	43
	; >>>>> printString("Task A is still running! Oh no! Task A was supposed to stop.\n"); 
	mov	ax, L_lab4b_app_9
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	44
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_lab4b_app_10:
	push	bp
	mov	bp, sp
	jmp	L_lab4b_app_11
L_lab4b_app_13:
	DB	"Task B started! Oh no! Task B wasn't supposed to run.",0xA,0
	ALIGN	2
BTask:
	; >>>>> Line:	48
	; >>>>> { 
	jmp	L_lab4b_app_14
L_lab4b_app_15:
	; >>>>> Line:	49
	; >>>>> printString("Task B started! Oh no! Task B wasn't supposed to run.\n"); 
	mov	ax, L_lab4b_app_13
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	50
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_lab4b_app_14:
	push	bp
	mov	bp, sp
	jmp	L_lab4b_app_15
L_lab4b_app_19:
	DB	"Executing in task C.",0xA,0
L_lab4b_app_18:
	DB	" context switches!",0xA,0
L_lab4b_app_17:
	DB	"Task C started after ",0
	ALIGN	2
CTask:
	; >>>>> Line:	54
	; >>>>> { 
	jmp	L_lab4b_app_20
L_lab4b_app_21:
	; >>>>> Line:	58
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	59
	; >>>>> numCtxSwitches = getYKCt 
	call	getYKCtxSwCount
	mov	word [bp-4], ax
	; >>>>> Line:	60
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	62
	; >>>>> printString("Task C started after "); 
	mov	ax, L_lab4b_app_17
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	63
	; >>>>> printUInt(numCtxSwitches); 
	push	word [bp-4]
	call	printUInt
	add	sp, 2
	; >>>>> Line:	64
	; >>>>> printString(" context switches!\n"); 
	mov	ax, L_lab4b_app_18
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	66
	; >>>>> while (1) 
	jmp	L_lab4b_app_23
L_lab4b_app_22:
	; >>>>> Line:	68
	; >>>>> printString("Executing in task C.\n"); 
	mov	ax, L_lab4b_app_19
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	69
	; >>>>> for(count = 0; count < 5000; count++); 
	mov	word [bp-2], 0
	jmp	L_lab4b_app_26
L_lab4b_app_25:
L_lab4b_app_28:
	inc	word [bp-2]
L_lab4b_app_26:
	cmp	word [bp-2], 5000
	jl	L_lab4b_app_25
L_lab4b_app_27:
L_lab4b_app_23:
	jmp	L_lab4b_app_22
L_lab4b_app_24:
	mov	sp, bp
	pop	bp
	ret
L_lab4b_app_20:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_lab4b_app_21
	ALIGN	2
AStk:
	TIMES	512 db 0
BStk:
	TIMES	512 db 0
CStk:
	TIMES	512 db 0
