        CPU     8086
        ORG     0h
InterruptVectorTable:
        ; Internal x86 Interrupts:
        dd      0 ; Reserved (Div err)  ; Int 00h
        dd      0 ; Reserved (Step)     ; Int 01h
        dd      0 ; Reserved (NMI)      ; Int 02h
        dd      0 ; Reserved (Break)    ; Int 03h
        dd      0 ; Reserved (Overflow) ; Int 04h
        dd      0                       ; Int 05h
        dd      0                       ; Int 06h
        dd      0                       ; Int 07h
        ; Hardware Interrupts:
        dd      RESET 		; Reset     ; Int 08h (IRQ 0)
        dd      TICK 		; Tick      ; Int 09h (IRQ 1)
        dd      KEYBOARD 	; Keyboard  ; Int 0Ah (IRQ 2)
        dd      0 ; Simptris Game Over  ; Int 0Bh (IRQ 3)
        dd      0 ; Simptris New Piece  ; Int 0Ch (IRQ 4)
        dd      0 ; Simptris Received   ; Int 0Dh (IRQ 5)
        dd      0 ; Simptris Touchdown  ; Int 0Eh (IRQ 6)
        dd      0 ; Simptris Clear      ; Int 0Fh (IRQ 7)
        ; Software Interrupts:
        dd      0 ; Reserved (PC BIOS)  ; Int 10h
        dd      0                       ; Int 11h
        dd      0                       ; Int 12h
        dd      0                       ; Int 13h
        dd      0                       ; Int 14h
        dd      0                       ; Int 15h
        dd      0                       ; Int 16h
        dd      0                       ; Int 17h
        dd      0                       ; Int 18h
        dd      0                       ; Int 19h
        dd      0                       ; Int 1Ah
        dd      0                       ; Int 1Bh
        dd      0                       ; Int 1Ch
        dd      0                       ; Int 1Dh
        dd      0                       ; Int 1Eh
        dd      0                       ; Int 1Fh
        dd      TRAP                    ; Int 20h
        dd      0 ; Reserved (DOS)      ; Int 21h
        dd      0 ; Simptris Services   ; Int 22h
        dd      0                       ; Int 23h
        dd      0                       ; Int 24h
        dd      0                       ; Int 25h
        dd      0                       ; Int 26h
        dd      0                       ; Int 27h
        dd      0                       ; Int 28h
        dd      0                       ; Int 29h
        dd      0                       ; Int 2Ah
        dd      0                       ; Int 2Bh
        dd      0                       ; Int 2Ch
        dd      0                       ; Int 2Dh
        dd      0                       ; Int 2Eh
        dd      0                       ; Int 2Fh
KeyBuffer:                              ; Address 0xC0
        dw      0
NewPieceType:                           ; Address 0xC2
        dw      0
NewPieceID:                             ; Address 0xC4
        dw      0
NewPieceOrientation:                    ; Address 0xC6
        dw      0
NewPieceColumn:                         ; Address 0xC8
        dw      0
TouchdownID:                            ; Address 0xCA
	dw	0
ScreenBitMap0:                          ; Address 0xCC
        dw      0
ScreenBitMap1:
        dw      0
ScreenBitMap2:
        dw      0
ScreenBitMap3:
        dw      0
ScreenBitMap4:
        dw      0
ScreenBitMap5:
        dw      0
TIMES   100h-($-$$) db  0               ; Fill up to (but not including) address 100h with 0
	jmp	main
; This file contains support routines for 32-bit on the 8086.
; It is intended for use code generated by the C86 compiler.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SR_asldiv:			; l1 /= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_ldiv
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmod:			; l1 %= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmod
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmul:			; l1 *= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmul
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshl:			; l1 <<= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshl
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshr:			; l1 >>= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshr
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


SR_asuldiv:			; u1 /= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_uldiv
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asilmod:			; u1 %= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ilmod
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulmul:			; u1 *= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulmul
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshl:			; u1 << u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshl
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshr:			; u1 >> u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshr
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


; Main 32-bit routines begin here:

SR_ldiv:	; N_LDIV@
	pop    cx
	push   cs
	push   cx
	; LDIV@
	xor    cx,cx
	jmp    LSR_01
SR_uldiv:	; N_LUDIV@
	pop    cx
	push   cs
	push   cx
	; F_LUDIV@
	mov    cx,0001
	jmp    LSR_01
SR_lmod:	; N_LMOD@
	pop    cx
	push   cs
	push   cx
	; F_LMOD@
	mov    cx,0002
	jmp    LSR_01
SR_ilmod:	; N_LUMOD@
	pop    cx
	push   cs
	push   cx
	; LUMOD@
	mov    cx,0003
LSR_01:
	push   bp
	push   si
	push   di
	mov    bp,sp
	mov    di,cx
	mov    ax,[bp+0Ah]
	mov    dx,[bp+0Ch]
	mov    bx,[bp+0Eh]
	mov    cx,[bp+10h]
	or     cx,cx
	jne    LSR_02
	or     dx,dx
	je     LSR_10
	or     bx,bx
	je     LSR_10
LSR_02:
	test   di,0001
	jne    LSR_04
	or     dx,dx
	jns    LSR_03
	neg    dx
	neg    ax
	sbb    dx,0000
	or     di,000Ch
LSR_03:
	or     cx,cx
	jns    LSR_04
	neg    cx
	neg    bx
	sbb    cx,0000
	xor    di,0004
LSR_04:
	mov    bp,cx
	mov    cx,0020h
	push   di
	xor    di,di
	xor    si,si
LSR_05:
	shl    ax,1
	rcl    dx,1
	rcl    si,1
	rcl    di,1
	cmp    di,bp
	jb     LSR_07
	ja     LSR_06
	cmp    si,bx
	jb     LSR_07
LSR_06:
	sub    si,bx
	sbb    di,bp
	inc    ax
LSR_07:
	loop   LSR_05
	pop    bx
	test   bx,0002
	je     LSR_08
	mov    ax,si
	mov    dx,di
	shr    bx,1
LSR_08:
	test   bx,0004h
	je     LSR_09
	neg    dx
	neg    ax
	sbb    dx,0000
LSR_09:
	pop    di
	pop    si
	pop    bp
	retf   0008
LSR_10:
	div    bx
	test   di,0002
	je     LSR_11
	xchg   dx,ax
LSR_11:
	xor    dx,dx
	jmp    LSR_09
SR_lshl:	; N_LXLSH@
SR_ulshl:
	; r = a << b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

	mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXLSH@
	cmp    cl,10h
	jnb    LSR_12
	mov    bx,ax
	shl    ax,cl
	shl    dx,cl
	neg    cl
	add    cl,10h
	shr    bx,cl
	or     dx,bx
	pop    cx
	pop    bp
	retf
LSR_12:
	sub    cl,10h
	xchg   dx,ax
	xor    ax,ax
	shl    dx,cl
	pop    cx
	pop    bp
	retf
SR_lshr:	; N_LXRSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXRSH@
	cmp    cl,10h
	jnb    LSR_13
	mov    bx,dx
	shr    ax,cl
	sar    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_13:
	sub    cl,10h
	xchg   dx,ax
	cwd
	sar    ax,cl
	pop    cx
	pop    bp
	retf
SR_ulshr:	; N_LXURSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXURSH@
	cmp    cl,10h
	jnb    LSR_14
	mov    bx,dx
	shr    ax,cl
	shr    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_14:
	sub    cl,10h
	xchg   dx,ax
	xor    dx,dx
	shr    ax,cl
	pop    cx
	pop    bp
	retf
SR_lmul:	; N_LXMUL@
SR_ulmul:
	; r = a * b
	push   bp
	push   si
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx
	push   bx

        mov    bx, [bp+6]	; pop loword(a)
	mov    cx, [bp+8]	; pop hiword(a)
	mov    ax, [bp+10]	; pop loword(b)
	mov    dx, [bp+12]	; pop hiword(b)
	
	xchg   si,ax
	xchg   dx,ax
	test   ax,ax
	je     LSR_15
	mul    bx
LSR_15:
	jcxz   LSR_16
	xchg   cx,ax
	mul    si
	add    ax,cx
LSR_16:
	xchg   si,ax
	mul    bx
	add    dx,si
	pop    bx
	pop    cx
	pop    si
	pop    bp
	ret

; Generated by c86 (BYU-NASM) 5.1 (beta) from clib.c
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
new_line:
	db	13,10,36
	ALIGN	2
signalEOI:
	jmp	L_clib_1
L_clib_2:
	mov	al, 0x20
	out	0x20, al
	mov	sp, bp
	pop	bp
	ret
L_clib_1:
	push	bp
	mov	bp, sp
	jmp	L_clib_2
	ALIGN	2
exit:
	jmp	L_clib_4
L_clib_5:
	mov	ah, 4Ch
	mov	al, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_4:
	push	bp
	mov	bp, sp
	jmp	L_clib_5
	ALIGN	2
print:
	jmp	L_clib_7
L_clib_8:
	mov	ah, 40h
	mov	bx, 1
	mov	cx, [bp+6]
	mov	dx, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_7:
	push	bp
	mov	bp, sp
	jmp	L_clib_8
	ALIGN	2
printChar:
	jmp	L_clib_10
L_clib_11:
	mov	ah, 2
	mov	dl, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_10:
	push	bp
	mov	bp, sp
	jmp	L_clib_11
	ALIGN	2
printNewLine:
	jmp	L_clib_13
L_clib_14:
	mov	ah, 9
	mov	dx, new_line
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_13:
	push	bp
	mov	bp, sp
	jmp	L_clib_14
	ALIGN	2
printString:
	jmp	L_clib_16
L_clib_17:
	xor	si,si
	mov	bx, [bp+4]
	jmp	printString2
	printString1:
	inc	si
	printString2:
	cmp	byte [bx+si],0
	jne	printString1
	mov	dx, bx
	mov	cx, si
	mov	ah, 40h
	mov	bx, 1
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_16:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_clib_17
	ALIGN	2
printInt:
	jmp	L_clib_19
L_clib_20:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	cmp	word [bp+4], 0
	jge	L_clib_21
	mov	byte [bp-10], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	neg	ax
	mov	word [bp+4], ax
L_clib_21:
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_22
	mov	word [bp-4], 1
	jmp	L_clib_23
L_clib_22:
	jmp	L_clib_25
L_clib_24:
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
L_clib_25:
	mov	ax, word [bp+4]
	cwd
	idiv	word [bp-4]
	test	ax, ax
	je	L_clib_24
L_clib_26:
L_clib_23:
	jmp	L_clib_28
L_clib_27:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	ax, dx
	mov	word [bp+4], ax
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
	mov	ax, word [bp-4]
	mov	word [bp-4], ax
L_clib_28:
	cmp	word [bp-4], 0
	jg	L_clib_27
L_clib_29:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_19:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_20
	ALIGN	2
printLong:
	jmp	L_clib_31
L_clib_32:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	cmp	word [bp+6], 0
	jg	L_clib_33
	jl	L_clib_34
	cmp	word [bp+4], 0
	jae	L_clib_33
L_clib_34:
	mov	byte [bp-17], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	neg	ax
	adc	dx, 0
	neg	dx
	mov	word [bp+4], ax
	mov	word [bp+6], dx
L_clib_33:
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_35
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_36
L_clib_35:
	jmp	L_clib_38
L_clib_37:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_38:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_ldiv
	or	dx, ax
	je	L_clib_37
L_clib_39:
L_clib_36:
	jmp	L_clib_41
L_clib_40:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_lmod
	mov	word [bp+4], ax
	mov	word [bp+6], dx
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_41:
	cmp	word [bp-4], 0
	jg	L_clib_40
	jne	L_clib_43
	cmp	word [bp-6], 0
	ja	L_clib_40
L_clib_43:
L_clib_42:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_31:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_32
	ALIGN	2
printUInt:
	jmp	L_clib_45
L_clib_46:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_47
	mov	word [bp-4], 1
	jmp	L_clib_48
L_clib_47:
	jmp	L_clib_50
L_clib_49:
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_50:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	test	ax, ax
	je	L_clib_49
L_clib_51:
L_clib_48:
	jmp	L_clib_53
L_clib_52:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	word [bp+4], dx
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_53:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_clib_52
L_clib_54:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_45:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_46
	ALIGN	2
printULong:
	jmp	L_clib_56
L_clib_57:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_58
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_59
L_clib_58:
	jmp	L_clib_61
L_clib_60:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_61:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	or	dx, ax
	je	L_clib_60
L_clib_62:
L_clib_59:
	jmp	L_clib_64
L_clib_63:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	lea	ax, [bp+4]
	push	ax
	call	SR_asilmod
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_64:
	mov	ax, word [bp-6]
	mov	dx, word [bp-4]
	or	dx, ax
	jne	L_clib_63
L_clib_65:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_56:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_57
	ALIGN	2
printByte:
	jmp	L_clib_67
L_clib_68:
	mov	al, byte [bp+4]
	cbw
	mov	cx, 4
	sar	ax, cl
	and	ax, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_69
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_70
L_clib_69:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_70:
	mov	byte [bp-3], al
	mov	al, byte [bp+4]
	and	al, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_71
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_72
L_clib_71:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_72:
	mov	byte [bp-2], al
	mov	ax, 2
	push	ax
	lea	ax, [bp-3]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_67:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_clib_68
	ALIGN	2
printWord:
	jmp	L_clib_74
L_clib_75:
	mov	word [bp-2], 3
	jmp	L_clib_77
L_clib_76:
	mov	ax, word [bp+4]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_80
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_81
L_clib_80:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_81:
	mov	si, word [bp-2]
	lea	dx, [bp-7]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp+4]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp+4], ax
L_clib_79:
	dec	word [bp-2]
L_clib_77:
	cmp	word [bp-2], 0
	jge	L_clib_76
L_clib_78:
	mov	ax, 4
	push	ax
	lea	ax, [bp-7]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_74:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_clib_75
	ALIGN	2
printDWord:
	jmp	L_clib_83
L_clib_84:
	lea	ax, [bp+4]
	mov	si, ax
	mov	ax, word [si]
	mov	word [bp-6], ax
	lea	ax, [bp+4]
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-8], ax
	mov	word [bp-2], 3
	jmp	L_clib_86
L_clib_85:
	mov	ax, word [bp-6]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_89
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_90
L_clib_89:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_90:
	mov	dx, word [bp-2]
	add	dx, 4
	mov	si, dx
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-6]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-6], ax
	mov	ax, word [bp-8]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_91
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_92
L_clib_91:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_92:
	mov	si, word [bp-2]
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-8]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-8], ax
L_clib_88:
	dec	word [bp-2]
L_clib_86:
	cmp	word [bp-2], 0
	jge	L_clib_85
L_clib_87:
	mov	ax, 8
	push	ax
	lea	ax, [bp-16]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_83:
	push	bp
	mov	bp, sp
	sub	sp, 16
	jmp	L_clib_84

RESET:

		call 	resetHandler	;calling C interrupt handler


TICK:

		push 	ax
		push 	bx
		push 	cx
		push 	dx
		push 	di
		push 	si
		push 	ds
		push 	es
		push 	bp
		call		YKGetISRCallDepth
		test		ax, ax
		jnz		tick_1
		mov		si, [currentTask]
		add		si, word 0x4
		mov 		[si], sp

tick_1:
		call	YKEnterISR

		sti					;enabling interrupts
		call	tickHandler		;calling C interrupt handler
		cli					;disabling interrupts

		mov 		al, 0x20			;Load nonspecific EOI value (0x20) into register al
		out		0x20, al		;Write EOI to PIC (port 0x20)

		call	YKExitISR

		pop		bp
		pop		es
		pop		ds
		pop		si
		pop		di
		pop		dx
		pop		cx
		pop		bx
		pop		ax

		iret					;returning from ISR

KEYBOARD:

		push 	ax
		push 	bx
		push 	cx
		push 	dx
		push 	di
		push 	si
		push 	ds
		push 	es
		push 	bp
		call		YKGetISRCallDepth
		test		ax, ax
		jnz		keyboard_1
		mov		si, [currentTask]
		add		si, word 0x4
		mov 		[si], sp	

keyboard_1:		
		call	YKEnterISR
		
		sti						;enabling interrupts
		call	keyboardHandler ;calling C interrupt handler
		cli						;disabling interrupts

		mov     al, 0x20		;Load nonspecific EOI value (0x20) into register al
		out		0x20, al		;Write EOI to PIC (port 0x20)

		call	YKExitISR

		pop		bp
		pop		es
		pop		ds
		pop		si
		pop		di
		pop		dx
		pop		cx
		pop		bx
		pop		ax

		iret					;returning from ISR

TRAP:

		push 	ax
		push 	bx
		push 	cx
		push 	dx
		push 	di
		push 	si
		push 	ds
		push 	es
		push 	bp
		mov		si, [currentTask]
		add		si, word 0x4
		mov 		[si], sp

		call 	YKScheduler

		pop		bp
		pop		es
		pop		ds
		pop		si
		pop		di
		pop		dx
		pop		cx
		pop		bx
		pop		ax

		iret

; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
resetHandler:
	; >>>>> Line:	9
	; >>>>> void resetHandler() { 
	jmp	L_myinth_1
L_myinth_2:
	; >>>>> Line:	10
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_1:
	push	bp
	mov	bp, sp
	jmp	L_myinth_2
L_myinth_4:
	DB	0xA,"Tick ",0
	ALIGN	2
tickHandler:
	; >>>>> Line:	13
	; >>>>> void tickHandler() { 
	jmp	L_myinth_5
L_myinth_6:
	; >>>>> Line:	17
	; >>>>> YKEnterMutex(); 
	mov	word [bp-2], 0
	; >>>>> Line:	17
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	18
	; >>>>> localCounter = ++YKTickCounter; 
	mov	ax, word [YKTickCounter]
	inc	ax
	mov	word [YKTickCounter], ax
	mov	word [bp-2], ax
	; >>>>> Line:	19
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	20
	; >>>>> printString("\nTick "); 
	mov	ax, L_myinth_4
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	21
	; >>>>> printInt(localCounter); 
	push	word [bp-2]
	call	printInt
	add	sp, 2
	; >>>>> Line:	22
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	23
	; >>>>> tickClock(); 
	call	tickClock
L_myinth_7:
	; >>>>> Line:	24
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_myinth_5:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_myinth_6
L_myinth_12:
	DB	") IGNORED",0xA,0
L_myinth_11:
	DB	0xA,"KEYPRESS (",0
L_myinth_10:
	DB	0xA,"DELAY COMPLETE",0xA,0
L_myinth_9:
	DB	0xA,"DELAY KEY PRESSED",0xA,0
	ALIGN	2
keyboardHandler:
	; >>>>> Line:	28
	; >>>>> void keyboardHandler() { 
	jmp	L_myinth_13
L_myinth_14:
	; >>>>> Line:	32
	; >>>>> if (KeyBuffer == 'd') { 
	cmp	word [KeyBuffer], 100
	jne	L_myinth_15
	; >>>>> Line:	33
	; >>>>> printString("\nDELAY KEY PRESSED\n"); 
	mov	ax, L_myinth_9
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	34
	; >>>>> for (i = 0; i < 5000; i++); 
	mov	word [bp-2], 0
	jmp	L_myinth_17
L_myinth_16:
L_myinth_19:
	inc	word [bp-2]
L_myinth_17:
	cmp	word [bp-2], 5000
	jl	L_myinth_16
L_myinth_18:
	; >>>>> Line:	35
	; >>>>> printString("\nD 
	mov	ax, L_myinth_10
	push	ax
	call	printString
	add	sp, 2
	jmp	L_myinth_20
L_myinth_15:
	; >>>>> Line:	36
	; >>>>> } else if (KeyBuffer == 'p') { 
	cmp	word [KeyBuffer], 112
	jne	L_myinth_21
	; >>>>> Line:	37
	; >>>>> YKSemPost(NSemPtr); 
	push	word [NSemPtr]
	call	YKSemPost
	add	sp, 2
	jmp	L_myinth_22
L_myinth_21:
	; >>>>> Line:	39
	; >>>>> printString("\nKEYPRESS ("); 
	mov	ax, L_myinth_11
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	40
	; >>>>> printChar((char) KeyBuffer); 
	push	word [KeyBuffer]
	call	printChar
	add	sp, 2
	; >>>>> Line:	41
	; >>>>> printString(") IGNORED\n"); 
	mov	ax, L_myinth_12
	push	ax
	call	printString
	add	sp, 2
L_myinth_22:
L_myinth_20:
L_myinth_23:
	; >>>>> Line:	44
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_myinth_13:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_myinth_14
YKIdleTask:
	
		push		bp
		mov		bp, sp

yak_loop:
		inc		word [YKIdleCount]		
		jmp		yak_loop

YKDispatcher:

		cli
		push 	bp
		mov		bp, sp		

		mov		bx, [bp+4]	;Obtain stack pointer from TCB
		mov		sp, [bx+4]	;Load stack pointer into SP

		pop		bp
		pop		es
		pop		ds
		pop		si
		pop		di
		pop		dx
		pop		cx
		pop		bx
		pop		ax

		iret

YKEnterMutex:

		cli
		ret

YKExitMutex:
		
		sti
		ret
; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKCtxSwCount:
	DW	0
YKIdleCount:
	DW	0
YKTickCounter:
	DW	0
L_yakc_1:
	DW	0
currentTask:
	DW	0
L_yakc_4:
	DW	0
	ALIGN	2
getYKCtxSwCount:
	; >>>>> Line:	22
	; >>>>> unsigned int getYKCtxSwCount() { 
	jmp	L_yakc_5
L_yakc_6:
	; >>>>> Line:	23
	; >>>>> return YKCtxSwCount; 
	mov	ax, word [YKCtxSwCount]
L_yakc_7:
	mov	sp, bp
	pop	bp
	ret
L_yakc_5:
	push	bp
	mov	bp, sp
	jmp	L_yakc_6
	ALIGN	2
getYKIdleCount:
	; >>>>> Line:	26
	; >>>>> unsigned int getYKIdleCount() { 
	jmp	L_yakc_9
L_yakc_10:
	; >>>>> Line:	27
	; >>>>> return YKIdleCount; 
	mov	ax, word [YKIdleCount]
L_yakc_11:
	mov	sp, bp
	pop	bp
	ret
L_yakc_9:
	push	bp
	mov	bp, sp
	jmp	L_yakc_10
	ALIGN	2
setYKIdleCount:
	; >>>>> Line:	30
	; >>>>> void setYKIdleCount(int value) { 
	jmp	L_yakc_13
L_yakc_14:
	; >>>>> Line:	31
	; >>>>> YKIdleCount = value; 
	mov	ax, word [bp+4]
	mov	word [YKIdleCount], ax
	mov	sp, bp
	pop	bp
	ret
L_yakc_13:
	push	bp
	mov	bp, sp
	jmp	L_yakc_14
	ALIGN	2
setYKCtxSwCount:
	; >>>>> Line:	34
	; >>>>> void setYKCtxSwCount(int value) { 
	jmp	L_yakc_16
L_yakc_17:
	; >>>>> Line:	35
	; >>>>> YKCtxSwCount = value; 
	mov	ax, word [bp+4]
	mov	word [YKCtxSwCount], ax
	mov	sp, bp
	pop	bp
	ret
L_yakc_16:
	push	bp
	mov	bp, sp
	jmp	L_yakc_17
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	39
	; >>>>> void YKEnterISR(void) { 
	jmp	L_yakc_19
L_yakc_20:
	; >>>>> Line:	40
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	41
	; >>>>> ISRCallDepth++; 
	inc	word [L_yakc_1]
	; >>>>> Line:	42
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_19:
	push	bp
	mov	bp, sp
	jmp	L_yakc_20
	ALIGN	2
YKExitISR:
	; >>>>> Line:	45
	; >>>>> void YKExitISR(void) { 
	jmp	L_yakc_22
L_yakc_23:
	; >>>>> Line:	46
	; >>>>> YKEnterMutex( 
	call	YKEnterMutex
	; >>>>> Line:	47
	; >>>>> ISRCallDepth--; 
	dec	word [L_yakc_1]
	; >>>>> Line:	48
	; >>>>> if (ISRCallDepth == 0) { 
	mov	ax, word [L_yakc_1]
	test	ax, ax
	jne	L_yakc_24
	; >>>>> Line:	49
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	50
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_24:
	mov	sp, bp
	pop	bp
	ret
L_yakc_22:
	push	bp
	mov	bp, sp
	jmp	L_yakc_23
	ALIGN	2
YKGetISRCallDepth:
	; >>>>> Line:	54
	; >>>>> unsigned int YKGetISRCallDepth(void) { 
	jmp	L_yakc_26
L_yakc_27:
	; >>>>> Line:	56
	; >>>>> return ISRCallDepth; 
	mov	ax, word [L_yakc_1]
L_yakc_28:
	mov	sp, bp
	pop	bp
	ret
L_yakc_26:
	push	bp
	mov	bp, sp
	jmp	L_yakc_27
	ALIGN	2
YKInitialize:
	; >>>>> Line:	59
	; >>>>> void YKInitialize(void) { 
	jmp	L_yakc_30
L_yakc_31:
	; >>>>> Line:	61
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	64
	; >>>>> initializePriorityQueue(&readyQueue); 
	mov	ax, readyQueue
	push	ax
	call	initializePriorityQueue
	add	sp, 2
	; >>>>> Line:	65
	; >>>>> initializeDelayQueue(); 
	call	initializeDelayQueue
	; >>>>> Line:	68
	; >>>>> taskBlock.nextFreeTCB == 0; 
	mov	ax, word [(154+taskBlock)]
	test	ax, ax
	je	L_yakc_32
	xor	ax, ax
	jmp	L_yakc_33
L_yakc_32:
	mov	ax, 1
L_yakc_33:
	; >>>>> Line:	72
	; >>>>> YKNewTask(YKIdleTask, &idleTaskStack[512], 100); 
	mov	al, 100
	push	ax
	mov	ax, (L_yakc_3+1024)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	75
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_34:
	; >>>>> Line:	76
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_30:
	push	bp
	mov	bp, sp
	jmp	L_yakc_31
	ALIGN	2
YKScheduler:
	; >>>>> Line:	80
	; >>>>> void YKScheduler(void) { 
	jmp	L_yakc_36
L_yakc_37:
	; >>>>> Line:	83
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	84
	; >>>>> if (kernelState == K_BLOCKED) return; 
	mov	ax, word [L_yakc_4]
	test	ax, ax
	jne	L_yakc_38
	; >>>>> Line:	84
	; >>>>> if (kernelState == K_BLOCKED) return; 
	jmp	L_yakc_39
L_yakc_38:
	; >>>>> Line:	85
	; >>>>> readyTask = peekPriorityQueue(&ready 
	mov	ax, readyQueue
	push	ax
	call	peekPriorityQueue
	add	sp, 2
	mov	word [bp-2], ax
	; >>>>> Line:	86
	; >>>>> if (readyTask == 0) exit(2); 
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_40
	; >>>>> Line:	86
	; >>>>> if (readyTask == 0) exit(2); 
	mov	al, 2
	push	ax
	call	exit
	add	sp, 2
L_yakc_40:
	; >>>>> Line:	87
	; >>>>> if (readyTask != currentTask) { 
	mov	ax, word [currentTask]
	cmp	ax, word [bp-2]
	je	L_yakc_41
	; >>>>> Line:	88
	; >>>>> currentTask = readyTask; 
	mov	ax, word [bp-2]
	mov	word [currentTask], ax
	; >>>>> Line:	89
	; >>>>> currentTask->state = T_READY; 
	mov	si, word [currentTask]
	add	si, 6
	mov	word [si], 1
	; >>>>> Line:	90
	; >>>>> YKCtxSwCount++; 
	inc	word [YKCtxSwCount]
	; >>>>> Line:	91
	; >>>>> readyTask->state = T_RUNNING; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 2
	; >>>>> Line:	92
	; >>>>> YKDispatcher(readyTask); 
	push	word [bp-2]
	call	YKDispatcher
	add	sp, 2
	; >>>>> Line:	93
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	94
	; >>>>> return; 
	jmp	L_yakc_39
L_yakc_41:
	; >>>>> Line:	96
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_39:
	; >>>>> Line:	97
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_36:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_37
	ALIGN	2
YKNewTask:
	; >>>>> Line:	100
	; >>>>> void YKNewTask(void (*task)(void), void* taskStack, unsigned char priority) { 
	jmp	L_yakc_43
L_yakc_44:
	; >>>>> Line:	105
	; >>>>> newTask = getNewTCB(); 
	call	getNewTCB
	mov	word [bp-2], ax
	; >>>>> Line:	106
	; >>>>> if (newTask == 0) exit(1); 
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_45
	; >>>>> Line:	106
	; >>>>> if (newTask == 0) exit(1); 
	mov	al, 1
	push	ax
	call	exit
	add	sp, 2
L_yakc_45:
	; >>>>> Line:	109
	; >>>>> newTask->tid = 0; 
	mov	si, word [bp-2]
	mov	word [si], 0
	; >>>>> Line:	110
	; >>>>> newTask->priority = priority; 
	mov	si, word [bp-2]
	add	si, 2
	mov	al, byte [bp+8]
	mov	byte [si], al
	; >>>>> Line:	111
	; >>>>> newTask->stackPointer = ((void*)((int*) taskSt 
	mov	ax, word [bp+6]
	sub	ax, 24
	mov	si, word [bp-2]
	add	si, 4
	mov	word [si], ax
	; >>>>> Line:	112
	; >>>>> newTask->state = T_READY; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 1
	; >>>>> Line:	113
	; >>>>> newTask->delayCount = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	114
	; >>>>> newTask->next = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	115
	; >>>>> newTask->prev = 0; 
	mov	si, word [bp-2]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	118
	; >>>>> asm("push bx"); 
	push bx
	; >>>>> Line:	119
	; >>>>> asm("push cx"); 
	push cx
	; >>>>> Line:	120
	; >>>>> asm("mov bx, [bp+6]"); 
	mov bx, [bp+6]
	; >>>>> Line:	121
	; >>>>> asm("mov cx, [bp+4]"); 
	mov cx, [bp+4]
	; >>>>> Line:	122
	; >>>>> asm("mov [bx-2], word 0x0200"); 
	mov [bx-2], word 0x0200
	; >>>>> Line:	123
	; >>>>> asm("mov [bx-4], word 0x0"); 
	mov [bx-4], word 0x0
	; >>>>> Line:	124
	; >>>>> asm("mov [bx-6], cx"); 
	mov [bx-6], cx
	; >>>>> Line:	125
	; >>>>> asm("pop cx"); 
	pop cx
	; >>>>> Line:	126
	; >>>>> asm("pop bx"); 
	pop bx
	; >>>>> Line:	128
	; >>>>> insertPriorityQueue(&readyQueue, newTask); 
	push	word [bp-2]
	mov	ax, readyQueue
	push	ax
	call	insertPriorityQueue
	add	sp, 4
	; >>>>> Line:	129
	; >>>>> asm("int 0x20"); 
	int 0x20
L_yakc_46:
	; >>>>> Line:	130
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_43:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_44
	ALIGN	2
getNewTCB:
	; >>>>> Line:	134
	; >>>>> TCB* getNewTCB(void) { 
	jmp	L_yakc_48
L_yakc_49:
	; >>>>> Line:	137
	; >>>>> if (taskBlock.nextFreeTCB < 10 + 1) { 
	cmp	word [(154+taskBlock)], 11
	jae	L_yakc_50
	; >>>>> Line:	138
	; >>>>> task = &taskBlock.TCBPool[taskBlock.nextFre 
	mov	ax, word [(154+taskBlock)]
	mov	cx, 14
	imul	cx
	add	ax, taskBlock
	mov	word [bp-2], ax
	; >>>>> Line:	139
	; >>>>> taskBlock.nextFreeTCB++; 
	inc	word [(154+taskBlock)]
	; >>>>> Line:	140
	; >>>>> return task; 
	mov	ax, word [bp-2]
	jmp	L_yakc_51
	jmp	L_yakc_52
L_yakc_50:
	; >>>>> Line:	142
	; >>>>> return 0; 
	xor	ax, ax
L_yakc_52:
L_yakc_51:
	mov	sp, bp
	pop	bp
	ret
L_yakc_48:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_49
	ALIGN	2
getNewSem:
	; >>>>> Line:	147
	; >>>>> YKSEM* getNewSem(void) { 
	jmp	L_yakc_54
L_yakc_55:
	; >>>>> Line:	150
	; >>>>> if (semBlock.nextFreeSem < 10) { 
	cmp	word [(80+L_yakc_2)], 10
	jae	L_yakc_56
	; >>>>> Line:	151
	; >>>>> semaphore = &semBlock.SemPool[semBlock.nextFreeSem]; 
	mov	ax, word [(80+L_yakc_2)]
	mov	cx, 3
	shl	ax, cl
	add	ax, L_yakc_2
	mov	word [bp-2], ax
	; >>>>> Line:	152
	; >>>>> semBlock.nextFreeSem++; 
	inc	word [(80+L_yakc_2)]
	; >>>>> Line:	153
	; >>>>> return semaphore; 
	mov	ax, word [bp-2]
	jmp	L_yakc_57
	jmp	L_yakc_58
L_yakc_56:
	; >>>>> Line:	155
	; >>>>> return 0; 
	xor	ax, ax
L_yakc_58:
L_yakc_57:
	mov	sp, bp
	pop	bp
	ret
L_yakc_54:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_55
	ALIGN	2
YKRun:
	; >>>>> Line:	160
	; >>>>> void YKRun(void) { 
	jmp	L_yakc_60
L_yakc_61:
	; >>>>> Line:	162
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	163
	; >>>>> kernelState = K_RUNNING; 
	mov	word [L_yakc_4], 1
	; >>>>> Line:	165
	; >>>>> YKScheduler(); 
	call	YKScheduler
	; >>>>> Line:	166
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_62:
	; >>>>> Line:	167
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_60:
	push	bp
	mov	bp, sp
	jmp	L_yakc_61
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	171
	; >>>>> void YKDelayTask(unsigned int count) { 
	jmp	L_yakc_64
L_yakc_65:
	; >>>>> Line:	175
	; >>>>> if (count == 0) return; 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_66
	; >>>>> Line:	175
	; >>>>> if (count == 0) return; 
	jmp	L_yakc_67
L_yakc_66:
	; >>>>> Line:	177
	; >>>>> delayedTask = removeP 
	mov	ax, readyQueue
	push	ax
	call	removePriorityQueue
	add	sp, 2
	mov	word [bp-2], ax
	; >>>>> Line:	178
	; >>>>> delayedTask->state = T_BLOCKED; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	179
	; >>>>> delayedTask->delayCount = count; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	180
	; >>>>> insertDelayQueue(delayedTask); 
	push	word [bp-2]
	call	insertDelayQueue
	add	sp, 2
	; >>>>> Line:	181
	; >>>>> asm("int 0x20"); 
	int 0x20
L_yakc_67:
	; >>>>> Line:	182
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_64:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_65
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	186
	; >>>>> void YKTickHandler(void) { 
	jmp	L_yakc_69
L_yakc_70:
	; >>>>> Line:	188
	; >>>>> tickClock(); 
	call	tickClock
	mov	sp, bp
	pop	bp
	ret
L_yakc_69:
	push	bp
	mov	bp, sp
	jmp	L_yakc_70
	ALIGN	2
readyQueue:
	TIMES	6 db 0
delayQueue:
	TIMES	4 db 0
taskBlock:
	TIMES	156 db 0
L_yakc_2:
	TIMES	82 db 0
L_yakc_3:
	TIMES	1024 db 0
; Generated by c86 (BYU-NASM) 5.1 (beta) from PriorityQueue.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
initializePriorityQueue:
	; >>>>> Line:	5
	; >>>>> void initializePriorityQueue(PriorityQueue* queue) { 
	jmp	L_PriorityQueue_1
L_PriorityQueue_2:
	; >>>>> Line:	6
	; >>>>> queue->size = 0; 
	mov	si, word [bp+4]
	add	si, 4
	mov	word [si], 0
	; >>>>> Line:	7
	; >>>>> queue->head = 0; 
	mov	si, word [bp+4]
	mov	word [si], 0
	; >>>>> Line:	8
	; >>>>> queue->tail = 0; 
	mov	si, word [bp+4]
	add	si, 2
	mov	word [si], 0
	mov	sp, bp
	pop	bp
	ret
L_PriorityQueue_1:
	push	bp
	mov	bp, sp
	jmp	L_PriorityQueue_2
	ALIGN	2
insertPriorityQueue:
	; >>>>> Line:	11
	; >>>>> void insertPriorityQueue(PriorityQueue* queue, TCB* tcb) { 
	jmp	L_PriorityQueue_4
L_PriorityQueue_5:
	; >>>>> Line:	15
	; >>>>> if(tcb == 0) return; 
	mov	ax, word [bp+6]
	test	ax, ax
	jne	L_PriorityQueue_6
	; >>>>> Line:	15
	; >>>>> if(tcb == 0) return; 
	jmp	L_PriorityQueue_7
L_PriorityQueue_6:
	; >>>>> Line:	18
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	19
	; >>>>> if (queue->size == 0) { 
	mov	si, word [bp+4]
	add	si, 4
	mov	ax, word [si]
	test	ax, ax
	jne	L_PriorityQueue_8
	; >>>>> Line:	20
	; >>>>> queue->head = tcb; 
	mov	si, word [bp+4]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	21
	; >>>>> queue->tail = tcb; 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	22
	; >>>>> > 
	mov	si, word [bp+6]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	23
	; >>>>> tcb->prev = 0; 
	mov	si, word [bp+6]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	24
	; >>>>> queue->size = 1; 
	mov	si, word [bp+4]
	add	si, 4
	mov	word [si], 1
	; >>>>> Line:	25
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	26
	; >>>>> return; 
	jmp	L_PriorityQueue_7
L_PriorityQueue_8:
	; >>>>> Line:	30
	; >>>>> if (queue->size == 1) { 
	mov	si, word [bp+4]
	add	si, 4
	cmp	word [si], 1
	jne	L_PriorityQueue_9
	; >>>>> Line:	31
	; >>>>> if (queue->head->priority < tcb->priority) { 
	mov	si, word [bp+4]
	mov	si, word [si]
	add	si, 2
	mov	di, word [bp+6]
	add	di, 2
	mov	al, byte [di]
	cmp	al, byte [si]
	jbe	L_PriorityQueue_10
	; >>>>> Line:	32
	; >>>>> queue->head->next = tcb; 
	mov	si, word [bp+4]
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	33
	; >>>>> tcb->prev = queue->head; 
	mov	si, word [bp+4]
	mov	di, word [bp+6]
	add	di, 12
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	34
	; >>>>> tcb->next = 0; 
	mov	si, word [bp+6]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	35
	; >>>>> queue->tail = tcb; 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	36
	; >>>>> queue->size++; 
	mov	si, word [bp+4]
	add	si, 4
	inc	word [si]
	; >>>>> Line:	37
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	38
	; >>>>> return; 
	jmp	L_PriorityQueue_7
	jmp	L_PriorityQueue_11
L_PriorityQueue_10:
	; >>>>> Line:	40
	; >>>>> tcb->next = queue->head; 
	mov	si, word [bp+4]
	mov	di, word [bp+6]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	41
	; >>>>> tcb->prev = 0; 
	mov	si, word [bp+6]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	42
	; >>>>> queue->tail->prev = tcb; 
	mov	si, word [bp+4]
	add	si, 2
	mov	si, word [si]
	add	si, 12
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	43
	; >>>>> queue->head = tcb; 
	mov	si, word [bp+4]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	44
	; >>>>> queue->size++; 
	mov	si, word [bp+4]
	add	si, 4
	inc	word [si]
	; >>>>> Line:	45
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	46
	; >>>>> return; 
	jmp	L_PriorityQueue_7
L_PriorityQueue_11:
L_PriorityQueue_9:
	; >>>>> Line:	51
	; >>>>> temp = queue->head; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	52
	; >>>>> while (temp != 0) { 
	jmp	L_PriorityQueue_13
L_PriorityQueue_12:
	; >>>>> Line:	53
	; >>>>> if (temp-> 
	mov	si, word [bp-2]
	add	si, 2
	mov	di, word [bp+6]
	add	di, 2
	mov	al, byte [di]
	cmp	al, byte [si]
	jae	L_PriorityQueue_15
	; >>>>> Line:	54
	; >>>>> tcb->next = temp; 
	mov	si, word [bp+6]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	55
	; >>>>> tcb->prev = temp->prev; 
	mov	si, word [bp-2]
	add	si, 12
	mov	di, word [bp+6]
	add	di, 12
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	56
	; >>>>> if (temp == queue->head) { 
	mov	si, word [bp+4]
	mov	ax, word [si]
	cmp	ax, word [bp-2]
	jne	L_PriorityQueue_16
	; >>>>> Line:	57
	; >>>>> queue->head = tcb; 
	mov	ax, word [bp+6]
	mov	word [si], ax
	jmp	L_PriorityQueue_17
L_PriorityQueue_16:
	; >>>>> Line:	59
	; >>>>> temp->prev->next = tcb; 
	mov	si, word [bp-2]
	add	si, 12
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp+6]
	mov	word [si], ax
L_PriorityQueue_17:
	; >>>>> Line:	61
	; >>>>> temp->prev = tcb; 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	62
	; >>>>> queue->size++; 
	mov	si, word [bp+4]
	add	si, 4
	inc	word [si]
	; >>>>> Line:	63
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	64
	; >>>>> return; 
	jmp	L_PriorityQueue_7
L_PriorityQueue_15:
	; >>>>> Line:	66
	; >>>>> temp = temp->next; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-2], ax
L_PriorityQueue_13:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_PriorityQueue_12
L_PriorityQueue_14:
	; >>>>> Line:	70
	; >>>>> queue->tail->next = tcb; 
	mov	si, word [bp+4]
	add	si, 2
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	71
	; >>>>> tcb->prev = queue->tail; 
	mov	si, word [bp+4]
	add	si, 2
	mov	di, word [bp+6]
	add	di, 12
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	72
	; >>>>> queue->tail = tcb; 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	73
	; >>>>> tcb->next = 0; 
	mov	si, word [bp+6]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	74
	; >>>>> queue->size++; 
	mov	si, word [bp+4]
	add	si, 4
	inc	word [si]
	; >>>>> Line:	75
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_PriorityQueue_7:
	; >>>>> Line:	76
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_PriorityQueue_4:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_PriorityQueue_5
	ALIGN	2
peekPriorityQueue:
	; >>>>> Line:	80
	; >>>>> TCB* peekPriorityQueue(PriorityQueue* queue) { 
	jmp	L_PriorityQueue_19
L_PriorityQueue_20:
	; >>>>> Line:	82
	; >>>>> return queue->head; 
	mov	si, word [bp+4]
	mov	ax, word [si]
L_PriorityQueue_21:
	mov	sp, bp
	pop	bp
	ret
L_PriorityQueue_19:
	push	bp
	mov	bp, sp
	jmp	L_PriorityQueue_20
	ALIGN	2
removePriorityQueue:
	; >>>>> Line:	86
	; >>>>> Value; 
	jmp	L_PriorityQueue_23
L_PriorityQueue_24:
	; >>>>> Line:	91
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	92
	; >>>>> if (queue->size == 0) { 
	mov	si, word [bp+4]
	add	si, 4
	mov	ax, word [si]
	test	ax, ax
	jne	L_PriorityQueue_25
	; >>>>> Line:	93
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	94
	; >>>>> return 0; 
	xor	ax, ax
	jmp	L_PriorityQueue_26
L_PriorityQueue_25:
	; >>>>> Line:	98
	; >>>>> if (queue->size == 1) { 
	mov	si, word [bp+4]
	add	si, 4
	cmp	word [si], 1
	jne	L_PriorityQueue_27
	; >>>>> Line:	99
	; >>>>> retValue = queue->head; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	100
	; >>>>> retValue->next = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	101
	; >>>>> retValue->prev = 0; 
	mov	si, word [bp-2]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	102
	; >>>>> queue->size--; 
	mov	si, word [bp+4]
	add	si, 4
	dec	word [si]
	; >>>>> Line:	103
	; >>>>> queue->head = 0; 
	mov	si, word [bp+4]
	mov	word [si], 0
	; >>>>> Line:	104
	; >>>>> queue->tail = 0; 
	mov	si, word [bp+4]
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	105
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	106
	; >>>>> return retValue; 
	mov	ax, word [bp-2]
	jmp	L_PriorityQueue_26
L_PriorityQueue_27:
	; >>>>> Line:	110
	; >>>>> retValue = queue->head; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	111
	; >>>>> queue->head = queue->head->next; 
	mov	si, word [bp+4]
	mov	si, word [si]
	add	si, 10
	mov	di, word [bp+4]
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	112
	; >>>>> queue->head->prev = 0; 
	mov	si, word [bp+4]
	mov	si, word [si]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	113
	; >>>>> queue->size--; 
	mov	si, word [bp+4]
	add	si, 4
	dec	word [si]
	; >>>>> Line:	114
	; >>>>> retValue->next = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	115
	; >>>>> retValue->prev = 0; 
	mov	si, word [bp-2]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	116
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	117
	; >>>>> return retValue; 
	mov	ax, word [bp-2]
L_PriorityQueue_26:
	mov	sp, bp
	pop	bp
	ret
L_PriorityQueue_23:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_PriorityQueue_24
	ALIGN	2
printPriorityQueue:
	; >>>>> Line:	121
	; >>>>> void printPriorityQueue(Priority 
	jmp	L_PriorityQueue_29
L_PriorityQueue_30:
	; >>>>> Line:	124
	; >>>>> while (current != 0) { 
	jmp	L_PriorityQueue_32
L_PriorityQueue_31:
	; >>>>> Line:	125
	; >>>>> printInt(current->priority); 
	mov	si, word [bp-2]
	add	si, 2
	mov	al, byte [si]
	xor	ah, ah
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	126
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	127
	; >>>>> current = current->next; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-2], ax
L_PriorityQueue_32:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_PriorityQueue_31
L_PriorityQueue_33:
	mov	sp, bp
	pop	bp
	ret
L_PriorityQueue_29:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_PriorityQueue_30
; Generated by c86 (BYU-NASM) 5.1 (beta) from DelayQueue.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
initializeDelayQueue:
	; >>>>> Line:	9
	; >>>>> void initializeDelayQueue() { 
	jmp	L_DelayQueue_1
L_DelayQueue_2:
	; >>>>> Line:	10
	; >>>>> delayQueue.size = 0; 
	mov	word [(2+delayQueue)], 0
	; >>>>> Line:	11
	; >>>>> delayQueue.head = 0; 
	mov	word [delayQueue], 0
	mov	sp, bp
	pop	bp
	ret
L_DelayQueue_1:
	push	bp
	mov	bp, sp
	jmp	L_DelayQueue_2
	ALIGN	2
tickClock:
	; >>>>> Line:	14
	; >>>>> (current 
	jmp	L_DelayQueue_4
L_DelayQueue_5:
	; >>>>> Line:	20
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	21
	; >>>>> if (delayQueue.size == 0) { 
	mov	ax, word [(2+delayQueue)]
	test	ax, ax
	jne	L_DelayQueue_6
	; >>>>> Line:	22
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	23
	; >>>>> return; 
	jmp	L_DelayQueue_7
L_DelayQueue_6:
	; >>>>> Line:	26
	; >>>>> current = delayQueue.head; 
	mov	ax, word [delayQueue]
	mov	word [bp-2], ax
	; >>>>> Line:	27
	; >>>>> if (delayQueue.size == 1) { 
	cmp	word [(2+delayQueue)], 1
	jne	L_DelayQueue_8
	; >>>>> Line:	28
	; >>>>> current->delayCount--; 
	mov	si, word [bp-2]
	add	si, 8
	dec	word [si]
	; >>>>> Line:	29
	; >>>>> if (current->delayCount == 0) { 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	jne	L_DelayQueue_9
	; >>>>> Line:	30
	; >>>>> delayQueue.head = 0; 
	mov	word [delayQueue], 0
	; >>>>> Line:	31
	; >>>>> delayQueue.size = 0; 
	mov	word [(2+delayQueue)], 0
	; >>>>> Line:	32
	; >>>>> current->next = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	33
	; >>>>> current->prev = 0; 
	mov	si, word [bp-2]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	34
	; >>>>> current->state = T_READY; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 1
	; >>>>> Line:	35
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	36
	; >>>>> insertPriorityQueue(&readyQueue, current); 
	push	word [bp-2]
	mov	ax, readyQueue
	push	ax
	call	insertPriorityQueue
	add	sp, 4
	; >>>>> Line:	38
	; >>>>> return; 
	jmp	L_DelayQueue_7
L_DelayQueue_9:
	; >>>>> Line:	40
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	41
	; >>>>> return; 
	jmp	L_DelayQueue_7
L_DelayQueue_8:
	; >>>>> Line:	44
	; >>>>> current->delayCount--; 
	mov	si, word [bp-2]
	add	si, 8
	dec	word [si]
	; >>>>> Line:	45
	; >>>>> while (current 
	jmp	L_DelayQueue_11
L_DelayQueue_10:
	; >>>>> Line:	46
	; >>>>> current = delayQueue.head; 
	mov	ax, word [delayQueue]
	mov	word [bp-2], ax
	; >>>>> Line:	47
	; >>>>> if (current->delayCount == 0) { 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	jne	L_DelayQueue_13
	; >>>>> Line:	48
	; >>>>> delayQueue.head = current->next; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [delayQueue], ax
	; >>>>> Line:	49
	; >>>>> if (current->next != 0) { 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	je	L_DelayQueue_14
	; >>>>> Line:	50
	; >>>>> current->next->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	si, word [si]
	add	si, 12
	mov	word [si], 0
L_DelayQueue_14:
	; >>>>> Line:	52
	; >>>>> current->next = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	53
	; >>>>> current->prev = 0; 
	mov	si, word [bp-2]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	54
	; >>>>> current->state = T_READY; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 1
	; >>>>> Line:	55
	; >>>>> temp = current; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
	; >>>>> Line:	56
	; >>>>> delayQueue.size--; 
	dec	word [(2+delayQueue)]
	; >>>>> Line:	57
	; >>>>> insertPriorityQueue(&readyQueue, temp); 
	push	word [bp-4]
	mov	ax, readyQueue
	push	ax
	call	insertPriorityQueue
	add	sp, 4
	; >>>>> Line:	58
	; >>>>> current = delayQueue.head; 
	mov	ax, word [delayQueue]
	mov	word [bp-2], ax
	jmp	L_DelayQueue_15
L_DelayQueue_13:
	; >>>>> Line:	60
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	61
	; >>>>> return; 
	jmp	L_DelayQueue_7
L_DelayQueue_15:
L_DelayQueue_11:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_DelayQueue_10
L_DelayQueue_12:
L_DelayQueue_7:
	mov	sp, bp
	pop	bp
	ret
L_DelayQueue_4:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_DelayQueue_5
	ALIGN	2
insertDelayQueue:
	; >>>>> Line:	67
	; >>>>> void insertDelayQueue(TCB* tcb) { 
	jmp	L_DelayQueue_17
L_DelayQueue_18:
	; >>>>> Line:	73
	; >>>>>  
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_DelayQueue_19
	; >>>>> Line:	73
	; >>>>>  
	jmp	L_DelayQueue_20
L_DelayQueue_19:
	; >>>>> Line:	76
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	77
	; >>>>> if (delayQueue.size == 0) { 
	mov	ax, word [(2+delayQueue)]
	test	ax, ax
	jne	L_DelayQueue_21
	; >>>>> Line:	78
	; >>>>> delayQueue.head = tcb; 
	mov	ax, word [bp+4]
	mov	word [delayQueue], ax
	; >>>>> Line:	79
	; >>>>> tcb->next = 0; 
	mov	si, word [bp+4]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	80
	; >>>>> tcb->prev = 0; 
	mov	si, word [bp+4]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	81
	; >>>>> delayQueue.size++; 
	inc	word [(2+delayQueue)]
	; >>>>> Line:	82
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	83
	; >>>>> return; 
	jmp	L_DelayQueue_20
L_DelayQueue_21:
	; >>>>> Line:	87
	; >>>>> current = delayQueue.head; 
	mov	ax, word [delayQueue]
	mov	word [bp-2], ax
	; >>>>> Line:	88
	; >>>>> sumCount = 0; 
	mov	word [bp-4], 0
	; >>>>> Line:	89
	; >>>>> oldSumCount = 0; 
	mov	word [bp-6], 0
	; >>>>> Line:	90
	; >>>>> while (current != 0) { 
	jmp	L_DelayQueue_23
L_DelayQueue_22:
	; >>>>> Line:	91
	; >>>>> sumCount += current->delayCount; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	add	word [bp-4], ax
	; >>>>> Line:	92
	; >>>>> if (tcb->delayCount < sumCount) { 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [bp-4]
	cmp	ax, word [si]
	jbe	L_DelayQueue_25
	; >>>>> Line:	93
	; >>>>> tcb->next = current; 
	mov	si, word [bp+4]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	94
	; >>>>> tcb->prev = current->prev; 
	mov	si, word [bp-2]
	add	si, 12
	mov	di, word [bp+4]
	add	di, 12
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	95
	; >>>>> if (current == delayQueue.head) { 
	mov	ax, word [delayQueue]
	cmp	ax, word [bp-2]
	jne	L_DelayQueue_26
	; >>>>> Line:	96
	; >>>>> tcb->dela 
	mov	ax, word [bp+4]
	mov	word [delayQueue], ax
	jmp	L_DelayQueue_27
L_DelayQueue_26:
	; >>>>> Line:	98
	; >>>>> current->prev->next = tcb; 
	mov	si, word [bp-2]
	add	si, 12
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp+4]
	mov	word [si], ax
L_DelayQueue_27:
	; >>>>> Line:	100
	; >>>>> current->prev = tcb; 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	101
	; >>>>> delayQueue.size++; 
	inc	word [(2+delayQueue)]
	; >>>>> Line:	102
	; >>>>> tcb->delayCount = tcb->delayCount - oldSumCount; 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	sub	ax, word [bp-6]
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], ax
	; >>>>> Line:	103
	; >>>>> current->delayCount = current->delayCount - tcb->delayCount; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	si, word [bp+4]
	add	si, 8
	sub	ax, word [si]
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], ax
	; >>>>> Line:	104
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	105
	; >>>>> return; 
	jmp	L_DelayQueue_20
L_DelayQueue_25:
	; >>>>> Line:	107
	; >>>>> if (current->next == 0) { 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_DelayQueue_28
	; >>>>> Line:	108
	; >>>>> current->next = tcb; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	109
	; >>>>> tcb->prev = current; 
	mov	si, word [bp+4]
	add	si, 12
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	110
	; >>>>> tcb->next = 0; 
	mov	si, word [bp+4]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	111
	; >>>>> delayQueue.size++; 
	inc	word [(2+delayQueue)]
	; >>>>> Line:	112
	; >>>>> tcb->dela 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	sub	ax, word [bp-4]
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], ax
	; >>>>> Line:	113
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	114
	; >>>>> return; 
	jmp	L_DelayQueue_20
L_DelayQueue_28:
	; >>>>> Line:	116
	; >>>>> current = current->next; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	117
	; >>>>> oldSumCount = sumCount; 
	mov	ax, word [bp-4]
	mov	word [bp-6], ax
L_DelayQueue_23:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_DelayQueue_22
L_DelayQueue_24:
L_DelayQueue_20:
	mov	sp, bp
	pop	bp
	ret
L_DelayQueue_17:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_DelayQueue_18
L_DelayQueue_30:
	DB	"Printing Delay Queue with size ",0
	ALIGN	2
printDelayQueue:
	; >>>>> Line:	122
	; >>>>> void printDelayQueue(void) { 
	jmp	L_DelayQueue_31
L_DelayQueue_32:
	; >>>>> Line:	127
	; >>>>> current = delayQueue.head; 
	mov	ax, word [delayQueue]
	mov	word [bp-2], ax
	; >>>>> Line:	128
	; >>>>> printString("Printing Delay Queue with size "); 
	mov	ax, L_DelayQueue_30
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	129
	; >>>>> printInt(delayQueue.size); 
	push	word [(2+delayQueue)]
	call	printInt
	add	sp, 2
	; >>>>> Line:	130
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	132
	; >>>>> while (current != 0) { 
	jmp	L_DelayQueue_34
L_DelayQueue_33:
	; >>>>> Line:	133
	; >>>>> printInt(current->priority); 
	mov	si, word [bp-2]
	add	si, 2
	mov	al, byte [si]
	xor	ah, ah
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	134
	; >>>>> printString(" "); 
	mov	ax, (L_DelayQueue_30+30)
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	135
	; >>>>> printInt(current->delayCount); 
	mov	si, word [bp-2]
	add	si, 8
	push	word [si]
	call	printInt
	add	sp, 2
	; >>>>> Line:	136
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	137
	; >>>>> current = current->next; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-2], ax
L_DelayQueue_34:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_DelayQueue_33
L_DelayQueue_35:
	mov	sp, bp
	pop	bp
	ret
L_DelayQueue_31:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_DelayQueue_32
; Generated by c86 (BYU-NASM) 5.1 (beta) from Semaphore.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKSemCreate:
	; >>>>> Line:	7
	; >>>>> YKSEM* YKSemCreate(int initialValue) { 
	jmp	L_Semaphore_1
L_Semaphore_2:
	; >>>>> Line:	10
	; >>>>> newSemaphore = getNewSem(); 
	call	getNewSem
	mov	word [bp-2], ax
	; >>>>> Line:	11
	; >>>>> if (newSemaphore == 0) exit(3); 
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_Semaphore_3
	; >>>>> Line:	11
	; >>>>> if (newSemaphore == 0) exit(3); 
	mov	al, 3
	push	ax
	call	exit
	add	sp, 2
L_Semaphore_3:
	; >>>>> Line:	13
	; >>>>> initializePriorityQueue(&(newSemaphore->queue)); 
	mov	ax, word [bp-2]
	add	ax, 2
	push	ax
	call	initializePriorityQueue
	add	sp, 2
	; >>>>> Line:	14
	; >>>>> newSemaphore->value = initialValue; 
	mov	si, word [bp-2]
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	16
	; >>>>> return newSemaphore; 
	mov	ax, word [bp-2]
L_Semaphore_4:
	mov	sp, bp
	pop	bp
	ret
L_Semaphore_1:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_Semaphore_2
	ALIGN	2
YKSemPend:
	; >>>>> Line:	20
	; >>>>> void YKSemPend(YKSEM* semaphore) { 
	jmp	L_Semaphore_6
L_Semaphore_7:
	; >>>>> Line:	24
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	25
	; >>>>> if (semaphore->value < 1) { 
	mov	si, word [bp+4]
	cmp	word [si], 1
	jge	L_Semaphore_8
	; >>>>> Line:	26
	; >>>>> semaphore->value--; 
	dec	word [si]
	; >>>>> Line:	27
	; >>>>> runningTask = removePriorityQueue(&readyQueue); 
	mov	ax, readyQueue
	push	ax
	call	removePriorityQueue
	add	sp, 2
	mov	word [bp-2], ax
	; >>>>> Line:	28
	; >>>>> runningTask->state = T_BLOCKED; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	29
	; >>>>> insertPriorityQueue((&(semaphore->queue)), runningTask); 
	push	word [bp-2]
	mov	ax, word [bp+4]
	add	ax, 2
	push	ax
	call	insertPriorityQueue
	add	sp, 4
	; >>>>> Line:	30
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	31
	; >>>>> asm("int 0x20"); 
	int 0x20
	; >>>>> Line:	32
	; >>>>> return; 
	jmp	L_Semaphore_9
	jmp	L_Semaphore_10
L_Semaphore_8:
	; >>>>> Line:	35
	; >>>>> semaphore->value--; 
	mov	si, word [bp+4]
	dec	word [si]
	; >>>>> Line:	36
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_Semaphore_10:
	; >>>>> Line:	37
	; >>>>> return; 
L_Semaphore_9:
	mov	sp, bp
	pop	bp
	ret
L_Semaphore_6:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_Semaphore_7
	ALIGN	2
YKSemPost:
	; >>>>> Line:	42
	; >>>>> void YKSemPost(YKSEM* semaphore) { 
	jmp	L_Semaphore_12
L_Semaphore_13:
	; >>>>> Line:	46
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	47
	; >>>>> semaphore->value++; 
	mov	si, word [bp+4]
	inc	word [si]
	; >>>>> Line:	48
	; >>>>> readyTask = removePriorityQueue(&(semaphore->queue)); 
	mov	ax, word [bp+4]
	add	ax, 2
	push	ax
	call	removePriorityQueue
	add	sp, 2
	mov	word [bp-2], ax
	; >>>>> Line:	49
	; >>>>> if (readyTask == 0) { 
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_Semaphore_14
	; >>>>> Line:	50
	; >>>>> YKE 
	call	YKExitMutex
	; >>>>> Line:	51
	; >>>>> return; 
	jmp	L_Semaphore_15
L_Semaphore_14:
	; >>>>> Line:	53
	; >>>>> readyTask->state = T_READY; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 1
	; >>>>> Line:	54
	; >>>>> insertPriorityQueue(&readyQueue, readyTask); 
	push	word [bp-2]
	mov	ax, readyQueue
	push	ax
	call	insertPriorityQueue
	add	sp, 4
	; >>>>> Line:	55
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	56
	; >>>>> if (YKGetISRCallDepth() == 0) { 
	call	YKGetISRCallDepth
	test	ax, ax
	jne	L_Semaphore_16
	; >>>>> Line:	57
	; >>>>> asm("int 0x20"); 
	int 0x20
L_Semaphore_16:
L_Semaphore_15:
	; >>>>> Line:	59
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_Semaphore_12:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_Semaphore_13
; Generated by c86 (BYU-NASM) 5.1 (beta) from lab5app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_lab5app_3:
	DB	"works",0
L_lab5app_2:
	DB	"it",0
L_lab5app_1:
	DB	"Hey",0
	ALIGN	2
TaskWord:
	; >>>>> Line:	24
	; >>>>> { 
	jmp	L_lab5app_4
L_lab5app_5:
	; >>>>> Line:	25
	; >>>>> while (1) 
	jmp	L_lab5app_7
L_lab5app_6:
	; >>>>> Line:	27
	; >>>>> YKSemPend(WSemPtr); 
	push	word [WSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	28
	; >>>>> printString("Hey"); 
	mov	ax, L_lab5app_1
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	29
	; >>>>> YKSemPost(PSemPtr); 
	push	word [PSemPtr]
	call	YKSemPost
	add	sp, 2
	; >>>>> Line:	31
	; >>>>> YKSemPend(WSemPtr); 
	push	word [WSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	32
	; >>>>> printString("it"); 
	mov	ax, L_lab5app_2
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	33
	; >>>>> YKSemPost(SSemPtr); 
	push	word [SSemPtr]
	call	YKSemPost
	add	sp, 2
	; >>>>> Line:	35
	; >>>>> YKSemPend(WSemPtr); 
	push	word [WSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	36
	; >>>>> printString("works"); 
	mov	ax, L_lab5app_3
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	37
	; >>>>> YKSemPost(PSemPtr); 
	push	word [PSemPtr]
	call	YKSemPost
	add	sp, 2
L_lab5app_7:
	jmp	L_lab5app_6
L_lab5app_8:
	mov	sp, bp
	pop	bp
	ret
L_lab5app_4:
	push	bp
	mov	bp, sp
	jmp	L_lab5app_5
	ALIGN	2
TaskSpace:
	; >>>>> Line:	42
	; >>>>> { 
	jmp	L_lab5app_10
L_lab5app_11:
	; >>>>> Line:	43
	; >>>>> while (1) 
	jmp	L_lab5app_13
L_lab5app_12:
	; >>>>> Line:	45
	; >>>>> YKSemPend(SSemPtr); 
	push	word [SSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	46
	; >>>>> printChar(' '); 
	mov	al, 32
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	47
	; >>>>> YKSemPost(WSemPtr); 
	push	word [WSemPtr]
	call	YKSemPost
	add	sp, 2
L_lab5app_13:
	jmp	L_lab5app_12
L_lab5app_14:
	mov	sp, bp
	pop	bp
	ret
L_lab5app_10:
	push	bp
	mov	bp, sp
	jmp	L_lab5app_11
L_lab5app_16:
	DB	"!",'"',0xD,0xA,0
	ALIGN	2
TaskPunc:
	; >>>>> Line:	52
	; >>>>> { 
	jmp	L_lab5app_17
L_lab5app_18:
	; >>>>> Line:	53
	; >>>>> while (1) 
	jmp	L_lab5app_20
L_lab5app_19:
	; >>>>> Line:	55
	; >>>>> YKSemPend(PSemPtr); 
	push	word [PSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	56
	; >>>>> printChar('"'); 
	mov	al, 34
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	57
	; >>>>> YKSemPost(WSemPtr); 
	push	word [WSemPtr]
	call	YKSemPost
	add	sp, 2
	; >>>>> Line:	59
	; >>>>> YKSemPend(PSemPtr); 
	push	word [PSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	60
	; >>>>> printChar(','); 
	mov	al, 44
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	61
	; >>>>> YKSemPost(SSemPtr); 
	push	word [SSemPtr]
	call	YKSemPost
	add	sp, 2
	; >>>>> Line:	63
	; >>>>> YKSemPend(PSemPtr); 
	push	word [PSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	64
	; >>>>> printString("!\"\r\n"); 
	mov	ax, L_lab5app_16
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	65
	; >>>>> YKSemPost(PSemPtr); 
	push	word [PSemPtr]
	call	YKSemPost
	add	sp, 2
	; >>>>> Line:	67
	; >>>>> YKDelayTask(6); 
	mov	ax, 6
	push	ax
	call	YKDelayTask
	add	sp, 2
L_lab5app_20:
	jmp	L_lab5app_19
L_lab5app_21:
	mov	sp, bp
	pop	bp
	ret
L_lab5app_17:
	push	bp
	mov	bp, sp
	jmp	L_lab5app_18
	ALIGN	2
TaskPrime:
	; >>>>> Line:	72
	; >>>>> { 
	jmp	L_lab5app_23
L_lab5app_24:
	; >>>>> Line:	77
	; >>>>> while (1) 
	mov	word [bp-2], 1001
	; >>>>> Line:	77
	; >>>>> while (1) 
	jmp	L_lab5app_26
L_lab5app_25:
	; >>>>> Line:	79
	; >>>>> YKSemPend(NSemPtr); 
	push	word [NSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	82
	; >>>>> lncnt = 0; 
	mov	word [bp-8], 0
	; >>>>> Line:	83
	; >>>>> endval = curval + 500; 
	mov	ax, word [bp-2]
	add	ax, 500
	mov	word [bp-10], ax
	; >>>>> Line:	84
	; >>>>> for ( ; c 
	jmp	L_lab5app_29
L_lab5app_28:
	; >>>>> Line:	86
	; >>>>> flag = 0; 
	mov	word [bp-6], 0
	; >>>>> Line:	87
	; >>>>> for (j = 3; (j*j) < curval; j += 2) 
	mov	word [bp-4], 3
	jmp	L_lab5app_33
L_lab5app_32:
	; >>>>> Line:	89
	; >>>>> if (curval % j == 0) 
	mov	ax, word [bp-2]
	cwd
	idiv	word [bp-4]
	mov	ax, dx
	test	ax, ax
	jne	L_lab5app_36
	; >>>>> Line:	91
	; >>>>> flag = 1; 
	mov	word [bp-6], 1
	; >>>>> Line:	92
	; >>>>> break; 
	jmp	L_lab5app_34
L_lab5app_36:
L_lab5app_35:
	add	word [bp-4], 2
L_lab5app_33:
	mov	ax, word [bp-4]
	imul	word [bp-4]
	mov	dx, word [bp-2]
	cmp	dx, ax
	jg	L_lab5app_32
L_lab5app_34:
	; >>>>> Line:	95
	; >>>>> if (!flag) 
	mov	ax, word [bp-6]
	test	ax, ax
	jne	L_lab5app_37
	; >>>>> Line:	97
	; >>>>> printChar(' '); 
	mov	al, 32
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	98
	; >>>>> printInt(curval); 
	push	word [bp-2]
	call	printInt
	add	sp, 2
	; >>>>> Line:	99
	; >>>>> lncnt++; 
	inc	word [bp-8]
	; >>>>> Line:	100
	; >>>>> if (lncnt > 9) 
	cmp	word [bp-8], 9
	jle	L_lab5app_38
	; >>>>> Line:	102
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	103
	; >>>>> lncnt = 0; 
	mov	word [bp-8], 0
L_lab5app_38:
L_lab5app_37:
L_lab5app_31:
	add	word [bp-2], 2
L_lab5app_29:
	mov	ax, word [bp-10]
	cmp	ax, word [bp-2]
	jg	L_lab5app_28
L_lab5app_30:
	; >>>>> Line:	107
	; >>>>> printNewLine(); 
	call	printNewLine
L_lab5app_26:
	jmp	L_lab5app_25
L_lab5app_27:
	mov	sp, bp
	pop	bp
	ret
L_lab5app_23:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_lab5app_24
L_lab5app_45:
	DB	", CPU usage: ",0
L_lab5app_44:
	DB	"<<<<< Context switches: ",0
L_lab5app_43:
	DB	"% >>>>>",0xD,0xA,0
L_lab5app_42:
	DB	"<<<<< max: ",0
L_lab5app_41:
	DB	"Determining CPU capacity",0xD,0xA,0
L_lab5app_40:
	DB	"Welcome to the YAK kernel",0xD,0xA,0
	ALIGN	2
TaskStat:
	; >>>>> Line:	112
	; >>>>> { 
	jmp	L_lab5app_46
L_lab5app_47:
	; >>>>> Line:	116
	; >>>>> YKDelayTask(1); 
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	117
	; >>>>> printString("Welcome to the YAK kernel\r\n"); 
	mov	ax, L_lab5app_40
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	118
	; >>>>> printString("Determining CPU capacity\r\n"); 
	mov	ax, L_lab5app_41
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	119
	; >>>>> YKDelayTask(1); 
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	121
	; >>>>> setYKIdleCount(0); 
	xor	ax, ax
	push	ax
	call	setYKIdleCount
	add	sp, 2
	; >>>>> Line:	122
	; >>>>> YKDelayTask(5); 
	mov	ax, 5
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	123
	; >>>>> max = getYKIdleCount() / 25; 
	call	getYKIdleCount
	cwd
	mov	cx, 25
	idiv	cx
	mov	word [bp-2], ax
	; >>>>> Line:	125
	; >>>>> printString ("<<<<< max: "); 
	mov	ax, L_lab5app_42
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	126
	; >>>>> printInt((int)max); 
	push	word [bp-2]
	call	printInt
	add	sp, 2
	; >>>>> Line:	127
	; >>>>> printString("% >>>>>\r\n"); 
	mov	ax, L_lab5app_43
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	131
	; >>>>> setYKIdleCount(0); 
	xor	ax, ax
	push	ax
	call	setYKIdleCount
	add	sp, 2
	; >>>>> Line:	133
	; >>>>> YKNewTask(TaskPrime, (v 
	mov	al, 32
	push	ax
	mov	ax, (TaskPRMStk+1024)
	push	ax
	mov	ax, TaskPrime
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	134
	; >>>>> YKNewTask(TaskWord, (void *) &TaskWStk[512], 10); 
	mov	al, 10
	push	ax
	mov	ax, (TaskWStk+1024)
	push	ax
	mov	ax, TaskWord
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	135
	; >>>>> YKNewTask(TaskSpace, (void *) &TaskSStk[512], 11); 
	mov	al, 11
	push	ax
	mov	ax, (TaskSStk+1024)
	push	ax
	mov	ax, TaskSpace
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	136
	; >>>>> YKNewTask(TaskPunc, (void *) &TaskPStk[512], 12); 
	mov	al, 12
	push	ax
	mov	ax, (TaskPStk+1024)
	push	ax
	mov	ax, TaskPunc
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	138
	; >>>>> while (1) 
	jmp	L_lab5app_49
L_lab5app_48:
	; >>>>> Line:	140
	; >>>>> YKDelayTask(20); 
	mov	ax, 20
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	142
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	143
	; >>>>> switchCount = getYKCtxSwCount(); 
	call	getYKCtxSwCount
	mov	word [bp-4], ax
	; >>>>> Line:	144
	; >>>>> idleCount = getYKIdleCount(); 
	call	getYKIdleCount
	mov	word [bp-6], ax
	; >>>>> Line:	145
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	147
	; >>>>> printString ("<<<<< Context switches: "); 
	mov	ax, L_lab5app_44
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	148
	; >>>>> printInt((int)switchCount); 
	push	word [bp-4]
	call	printInt
	add	sp, 2
	; >>>>> Line:	149
	; >>>>> printString(", CPU usage: "); 
	mov	ax, L_lab5app_45
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	150
	; >>>>> tmp = (int) ( 
	mov	ax, word [bp-6]
	xor	dx, dx
	div	word [bp-2]
	mov	word [bp-8], ax
	; >>>>> Line:	151
	; >>>>> printInt(100-tmp); 
	mov	ax, 100
	sub	ax, word [bp-8]
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	152
	; >>>>> printString("% >>>>>\r\n"); 
	mov	ax, L_lab5app_43
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	154
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	157
	; >>>>> setYKIdleCount(0); 
	xor	ax, ax
	push	ax
	call	setYKIdleCount
	add	sp, 2
	; >>>>> Line:	158
	; >>>>> setYKCtxSwCount(0); 
	xor	ax, ax
	push	ax
	call	setYKCtxSwCount
	add	sp, 2
	; >>>>> Line:	159
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_lab5app_49:
	jmp	L_lab5app_48
L_lab5app_50:
	mov	sp, bp
	pop	bp
	ret
L_lab5app_46:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_lab5app_47
	ALIGN	2
main:
	; >>>>> Line:	164
	; >>>>> { 
	jmp	L_lab5app_52
L_lab5app_53:
	; >>>>> Line:	165
	; >>>>> YKInitialize(); 
	call	YKInitialize
	; >>>>> Line:	168
	; >>>>> PSemPtr = YKSemCreate(1); 
	mov	ax, 1
	push	ax
	call	YKSemCreate
	add	sp, 2
	mov	word [PSemPtr], ax
	; >>>>> Line:	169
	; >>>>> SSemPtr = YKSemCreate(0); 
	xor	ax, ax
	push	ax
	call	YKSemCreate
	add	sp, 2
	mov	word [SSemPtr], ax
	; >>>>> Line:	170
	; >>>>> WSemPtr = YKSemCreate(0); 
	xor	ax, ax
	push	ax
	call	YKSemCreate
	add	sp, 2
	mov	word [WSemPtr], ax
	; >>>>> Line:	171
	; >>>>> NSemPtr = YKSemCreate(0); 
	xor	ax, ax
	push	ax
	call	YKSemCreate
	add	sp, 2
	mov	word [NSemPtr], ax
	; >>>>> Line:	172
	; >>>>> YKNewTask(TaskStat, (void *) &TaskStatStk[512], 30); 
	mov	al, 30
	push	ax
	mov	ax, (TaskStatStk+1024)
	push	ax
	mov	ax, TaskStat
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	174
	; >>>>> YKRun(); 
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_lab5app_52:
	push	bp
	mov	bp, sp
	jmp	L_lab5app_53
	ALIGN	2
TaskWStk:
	TIMES	1024 db 0
TaskSStk:
	TIMES	1024 db 0
TaskPStk:
	TIMES	1024 db 0
TaskStatStk:
	TIMES	1024 db 0
TaskPRMStk:
	TIMES	1024 db 0
PSemPtr:
	TIMES	2 db 0
SSemPtr:
	TIMES	2 db 0
WSemPtr:
	TIMES	2 db 0
NSemPtr:
	TIMES	2 db 0
